# Generated by Django 4.2.16 on 2025-10-30 17:52

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staff", "0006_alter_helixstaff_communication_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0012_building_is_active_floor_is_active_unit_is_active"),
        ("residents", "0009_residenteviction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("slot_date", models.DateField(db_index=True)),
                ("slot_start_time", models.TimeField()),
                ("slot_end_time", models.TimeField()),
                ("slot_duration_minutes", models.IntegerField(default=30)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("total_bookings", models.IntegerField(default=0)),
                ("max_concurrent_bookings", models.IntegerField(default=1)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="locations.amenity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Slot",
                "verbose_name_plural": "Amenity Slots",
            },
        ),
        migrations.CreateModel(
            name="AmenityBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "display_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "selected_slot_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of selected AmenitySlot UUIDs for extended bookings",
                    ),
                ),
                ("booking_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("booking_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("confirmed", "CONFIRMED"),
                            ("rejected", "REJECTED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "rejection_reason",
                    lookup.fields.LookupField(
                        blank=True,
                        lookup_name="BOOKING_REJECTION_REASON",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("rejection_remarks", models.TextField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("confirmed_on", models.DateTimeField(blank=True, null=True)),
                ("rejected_on", models.DateTimeField(blank=True, null=True)),
                ("cancelled_on", models.DateTimeField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(db_index=True, default=False)),
                (
                    "repeat_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_required", "NOT_REQUIRED"),
                            ("weekly", "WEEKLY"),
                            ("biweekly", "BIWEEKLY"),
                            ("monthly", "MONTHLY"),
                            ("custom", "CUSTOM"),
                        ],
                        help_text="DAILY, WEEKLY, MONTHLY, YEARLY",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "repeat_interval",
                    models.IntegerField(
                        default=1,
                        help_text="Every N days/weeks/months (e.g., 2 = every 2 weeks)",
                    ),
                ),
                (
                    "repeat_on_days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["monday", "wednesday", "friday"]',
                    ),
                ),
                (
                    "repeat_on_day_of_month",
                    models.IntegerField(
                        blank=True, help_text="1-31 or -1 for last day", null=True
                    ),
                ),
                (
                    "recurrence_end_type",
                    models.CharField(
                        choices=[
                            ("never", "Never ends"),
                            ("after_occurrences", "After N occurrences"),
                            ("on_date", "On specific date"),
                        ],
                        default="never",
                        max_length=50,
                    ),
                ),
                (
                    "recurrence_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date to create recurring bookings",
                        null=True,
                    ),
                ),
                (
                    "recurrence_occurrences",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of occurrences to generate",
                        null=True,
                    ),
                ),
                (
                    "occurrence_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="For recurring instances, the date of this occurrence",
                        null=True,
                    ),
                ),
                (
                    "recurrence_sequence",
                    models.IntegerField(
                        blank=True,
                        help_text="Occurrence number in the series (1st, 2nd, 3rd...)",
                        null=True,
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="locations.amenity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_confirmed",
                        to="staff.helixstaff",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_booking",
                    models.ForeignKey(
                        help_text="Parent booking if this is a recurring instance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_instances",
                        to="bookings.amenitybooking",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        help_text="Associated slot if created from slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="bookings.amenityslot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_bookings",
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Booking",
                "verbose_name_plural": "Amenity Bookings",
            },
        ),
        migrations.CreateModel(
            name="AmenityBlackoutPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_periods",
                        to="locations.amenity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blackout_periods_created",
                        to="staff.helixstaff",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Blackout Period",
                "verbose_name_plural": "Amenity Blackout Periods",
            },
        ),
        migrations.CreateModel(
            name="RecurrenceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("occurrence_date", models.DateField(db_index=True)),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("skip", "Skip this occurrence"),
                            ("modify", "Modify this occurrence"),
                            ("cancel", "Cancel this occurrence"),
                        ],
                        max_length=50,
                    ),
                ),
                ("new_start_time", models.TimeField(blank=True, null=True)),
                ("new_end_time", models.TimeField(blank=True, null=True)),
                ("new_booking_date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.helixstaff",
                    ),
                ),
                (
                    "parent_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_exceptions",
                        to="bookings.amenitybooking",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_booking", "occurrence_date")},
            },
        ),
        migrations.AddIndex(
            model_name="amenityslot",
            index=models.Index(
                fields=["amenity", "slot_date"], name="bookings_am_amenity_92eda0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenityslot",
            index=models.Index(
                fields=["amenity", "slot_date", "is_available"],
                name="bookings_am_amenity_fdbbe8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="amenityslot",
            unique_together={("amenity", "slot_date", "slot_start_time")},
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["amenity", "booking_date"],
                name="bookings_am_amenity_6ed821_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["amenity", "booking_date", "status"],
                name="bookings_am_amenity_2e79eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["tenant", "status"], name="bookings_am_tenant__a19eee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["status", "booking_date"], name="bookings_am_status_20c50a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["is_recurring", "parent_booking"],
                name="bookings_am_is_recu_990124_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["parent_booking", "occurrence_date"],
                name="bookings_am_parent__7a5da7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenityblackoutperiod",
            index=models.Index(
                fields=["amenity", "start_date", "end_date"],
                name="bookings_am_amenity_78e505_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenityblackoutperiod",
            index=models.Index(
                fields=["amenity", "active", "start_date"],
                name="bookings_am_amenity_15b42d_idx",
            ),
        ),
    ]
