# Generated by Django 4.2.16 on 2025-05-27 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helixuser",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="helixuser",
            name="languages_known",
        ),
        migrations.RemoveField(
            model_name="helixuser",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="helixuser",
            name="matrix_json",
        ),
        migrations.RemoveField(
            model_name="helixuser",
            name="sexual_orientation",
        ),
        migrations.AlterField(
            model_name="helixuser",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("property", "Property"),
                    ("location", "Location"),
                    ("building", "Building"),
                    ("floor", "Floor"),
                    ("unit", "Unit"),
                ],
                default="location",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="helixuser",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                max_length=255,
                unique=True,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
    ]
