# Generated by Django 4.2.16 on 2025-05-28 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0002_remove_helixuser_default_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="helixuser",
            old_name="staff",
            new_name="is_staff",
        ),
    ]
