# Generated by Django 4.2.16 on 2025-06-11 08:51

import django.contrib.postgres.fields
from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0003_rename_staff_helixuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="helixuser",
            name="languages_known",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    blank=True, lookup_name="LANGUAGE", max_length=50, null=True
                ),
                default=list,
                size=None,
            ),
        ),
    ]
