# Generated by Django 4.2.16 on 2025-06-12 06:16

import django.contrib.postgres.fields
from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0004_helixuser_languages_known"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helixuser",
            name="languages_known",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="LANGUAGE", max_length=50
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="helixuser",
            name="status",
            field=lookup.fields.LookupField(
                blank=True,
                default="PENDING",
                lookup_name="USER_ACTIVATION_STATUS",
                max_length=50,
                null=True,
            ),
        ),
    ]
