# Generated by Django 4.2.16 on 2025-11-04 20:03

from django.db import migrations, models
import django.db.models.deletion
import lookup.fields


def fix_duplicate_version_numbers(apps, schema_editor):
    """
    Fix duplicate version numbers for PolicyVersion records.
    For each policy, reassign version numbers sequentially starting from 1.
    """
    Policy = apps.get_model("helixauth", "Policy")
    PolicyVersion = apps.get_model("helixauth", "PolicyVersion")

    # Get all policies
    for policy in Policy.objects.all():
        # Get all versions for this policy, ordered by creation date
        versions = PolicyVersion.objects.filter(policy=policy).order_by("created_on")

        # Reassign version numbers sequentially
        for index, version in enumerate(versions, start=1):
            version.version_number = index
            version.save()


def reverse_fix(apps, schema_editor):
    """Reverse is not needed as we're just fixing data"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
        ("helixauth", "0005_alter_helixuser_languages_known_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterModelOptions(
            name="policyversion",
            options={"ordering": ["-version_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="policyversion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="policy",
            name="active",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="doc_type",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="start_date",
        ),
        migrations.AddField(
            model_name="policy",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_in_policy",
                to="helixauth.policyversion",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_type",
            field=lookup.fields.LookupField(
                default="RENT_PAYMENT", lookup_name="POLICY_TYPE", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="publishing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="status",
            field=lookup.fields.LookupField(
                default="DRAFT", lookup_name="POLICY_STATUS", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="content_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="template_pdf_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_version_pdfs",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(fix_duplicate_version_numbers, reverse_fix),
        migrations.AlterUniqueTogether(
            name="policyversion",
            unique_together={("policy", "version_number")},
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["status", "-created_on"], name="helixauth_p_status_257994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(fields=["name"], name="helixauth_p_name_e64c63_idx"),
        ),
        migrations.RemoveField(
            model_name="policyversion",
            name="content",
        ),
        migrations.RemoveField(
            model_name="policyversion",
            name="policy_version",
        ),
    ]
