# Generated by Django 4.2.16 on 2025-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0006_update_policy_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registereddevice",
            unique_together={("user", "make", "model", "mac_address")},
        ),
        migrations.AddField(
            model_name="registereddevice",
            name="device_fingerprint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="registereddevice",
            unique_together={
                ("user", "device_fingerprint"),
                ("user", "make", "model", "mac_address"),
            },
        ),
    ]
