# Generated by Django 4.2.16 on 2025-06-12 12:34

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "home_phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("home_phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "service_type",
                    lookup.fields.LookupField(
                        lookup_name="MAINTENANCE_SERVICE_TYPE", max_length=255
                    ),
                ),
                (
                    "languages_known",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="LANGUAGE", max_length=50
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceProviderDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "document_type",
                    lookup.fields.LookupField(
                        lookup_name="IDENTITY_LIST", max_length=40
                    ),
                ),
                (
                    "document_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="service_provider_document_back_image",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "front_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="service_provider_document_front_image",
                        to="assets.asset",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="maintenance.serviceprovider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
