# Generated by Django 4.2.16 on 2025-06-30 15:26

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("residents", "0007_alter_residentdocument_back_image_and_more"),
        (
            "locations",
            "0009_customer_home_phone_customer_home_phone_country_code_and_more",
        ),
        ("assets", "0002_initial"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "home_phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("home_phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("service_title", models.CharField(max_length=255)),
                (
                    "service_type",
                    lookup.fields.LookupField(
                        lookup_name="MAINTENANCE_SERVICE_TYPE", max_length=255
                    ),
                ),
                (
                    "service_priority",
                    lookup.fields.LookupField(
                        lookup_name="MAINTENANCE_SERVICE_PRIORITY", max_length=255
                    ),
                ),
                ("reported_date", models.DateField()),
                ("due_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("rejected", "REJECTED"),
                        ],
                        default="open",
                        max_length=255,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="maintenance.serviceprovider",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(blank=True, null=True, to="assets.asset"),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residents.resident",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locations.unit"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
