# Generated by Django 4.2.16 on 2025-10-24 06:24

from django.db import migrations, models
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0002_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="reject_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="reject_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="reject_reason",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="MAINTENANCE_REJECT_REASON",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="resolved_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
