# Generated by Django 4.2.16 on 2025-11-06 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_initial"),
        (
            "maintenance",
            "0003_maintenance_reject_date_maintenance_reject_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="preferred_contact_method",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="COMMUNICATION_MODE", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="preferred_maintenance_requests",
                to="maintenance.serviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="recurring_issue",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="MAINTENANCE_RECURRING_FREQUENCY",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assigned_maintenance_requests",
                to="maintenance.serviceprovider",
            ),
        ),
    ]
