# Generated by Django 4.2.16 on 2025-11-18 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_serviceprovider_average_rating_and_more"),
        ("maintenance", "0004_maintenance_estimated_cost_and_more"),
    ]

    operations = []
