# Generated by Django 4.2.16 on 2026-01-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0005_merge_20251118_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("approved", "APPROVED"),
                    ("in_progress", "IN_PROGRESS"),
                    ("completed", "COMPLETED"),
                    ("rejected", "REJECTED"),
                ],
                default="open",
                max_length=255,
            ),
        ),
    ]
