//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resido.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resido.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number or email is required..
        /// </summary>
        public static string ContactOrEmail_Required {
            get {
                return ResourceManager.GetString("ContactOrEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your contact number first, and then continue..
        /// </summary>
        public static string ContactVerificationRequired {
            get {
                return ResourceManager.GetString("ContactVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial code must start with &apos;+&apos; followed by digits..
        /// </summary>
        public static string DialCode_Invalid {
            get {
                return ResourceManager.GetString("DialCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial code is required..
        /// </summary>
        public static string DialCode_Required {
            get {
                return ResourceManager.GetString("DialCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered..
        /// </summary>
        public static string Email_AlreadyExists {
            get {
                return ResourceManager.GetString("Email_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email exists but is not verified. Please verify your email..
        /// </summary>
        public static string Email_NotVerified {
            get {
                return ResourceManager.GetString("Email_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address and phone number to continue..
        /// </summary>
        public static string EmailAndPhoneVerificationRequired {
            get {
                return ResourceManager.GetString("EmailAndPhoneVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        public static string EmailBestRegards {
            get {
                return ResourceManager.GetString("EmailBestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZafeLock Team.
        /// </summary>
        public static string EmailTeam {
            get {
                return ResourceManager.GetString("EmailTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email first, and then continue..
        /// </summary>
        public static string EmailVerificationRequired {
            get {
                return ResourceManager.GetString("EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token. Please login again..
        /// </summary>
        public static string InvalidAccessToken {
            get {
                return ResourceManager.GetString("InvalidAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP..
        /// </summary>
        public static string InvalidOtp {
            get {
                return ResourceManager.GetString("InvalidOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP sending medium..
        /// </summary>
        public static string InvalidOtpSendingMedium {
            get {
                return ResourceManager.GetString("InvalidOtpSendingMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or phone number format..
        /// </summary>
        public static string InvalidPhoneEmail {
            get {
                return ResourceManager.GetString("InvalidPhoneEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unauthorized smart lock..
        /// </summary>
        public static string InvalidSmartLock {
            get {
                return ResourceManager.GetString("InvalidSmartLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password. Please try again..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a one-time code to your email. Please check and verify your email address..
        /// </summary>
        public static string OneTimeCodeToEmail {
            get {
                return ResourceManager.GetString("OneTimeCodeToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time code has been sent to your phone..
        /// </summary>
        public static string OneTimeCodeToPhone {
            get {
                return ResourceManager.GetString("OneTimeCodeToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-time password has expired..
        /// </summary>
        public static string OneTimePassword {
            get {
                return ResourceManager.GetString("OneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to send the one-time code to your email. Please try again later..
        /// </summary>
        public static string OTPNotSendToEmail {
            get {
                return ResourceManager.GetString("OTPNotSendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the one-time code to your phone..
        /// </summary>
        public static string OTPNotSendToPhone {
            get {
                return ResourceManager.GetString("OTPNotSendToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your phone, we have sent you a one-time password..
        /// </summary>
        public static string OtpSend {
            get {
                return ResourceManager.GetString("OtpSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email, we have sent you a one-time password..
        /// </summary>
        public static string OtpSendEmail {
            get {
                return ResourceManager.GetString("OtpSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password already exists. Please try logging in..
        /// </summary>
        public static string Password_Already_Created {
            get {
                return ResourceManager.GetString("Password_Already_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters, include uppercase, number, and special character..
        /// </summary>
        public static string Password_Invalid {
            get {
                return ResourceManager.GetString("Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        public static string Password_Not_Match {
            get {
                return ResourceManager.GetString("Password_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is already registered..
        /// </summary>
        public static string PhoneNumber_AlreadyExists {
            get {
                return ResourceManager.GetString("PhoneNumber_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must contain digits only..
        /// </summary>
        public static string PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number exists but is not verified. Please verify your phone number..
        /// </summary>
        public static string PhoneNumber_NotVerified {
            get {
                return ResourceManager.GetString("PhoneNumber_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string PhoneNumber_Required {
            get {
                return ResourceManager.GetString("PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your password..
        /// </summary>
        public static string RepeatPassword_Required {
            get {
                return ResourceManager.GetString("RepeatPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try to resend the OTP after {0} seconds.
        /// </summary>
        public static string ResentOtpAfterTime {
            get {
                return ResourceManager.GetString("ResentOtpAfterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zafe Lock: One-Time Code to Reset Your Password.
        /// </summary>
        public static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the OTP first, then verify it..
        /// </summary>
        public static string SendOtpBeforeVerification {
            get {
                return ResourceManager.GetString("SendOtpBeforeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Zafe Lock verification code is: {0}.
        /// </summary>
        public static string SmsBody {
            get {
                return ResourceManager.GetString("SmsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zafe Lock: Confirm Your Email Address.
        /// </summary>
        public static string SubjectVerifyEmail {
            get {
                return ResourceManager.GetString("SubjectVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access!.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this one-time code to change your email address. &lt;br&gt; One-time Code: {0} &lt;br&gt; (Valid for 5 minutes).
        /// </summary>
        public static string UpdateEmailOtp {
            get {
                return ResourceManager.GetString("UpdateEmailOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following one-time code to reset your Zafe Lock password: {0}.
        /// </summary>
        public static string UpdatePasswordOtp {
            get {
                return ResourceManager.GetString("UpdatePasswordOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the one-time code below to change your phone number in Zafe Connect: {0}.
        /// </summary>
        public static string UpdateUserPhone {
            get {
                return ResourceManager.GetString("UpdateUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ZafeLock – Your Access Details Inside.
        /// </summary>
        public static string WelcomeToZafeLockEkeySubject {
            get {
                return ResourceManager.GetString("WelcomeToZafeLockEkeySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to create your Zafe account..
        /// </summary>
        public static string ZafeAccountCreationError {
            get {
                return ResourceManager.GetString("ZafeAccountCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zafe Lock – Email Update OTP.
        /// </summary>
        public static string ZafeLockEmailUpdateOTP {
            get {
                return ResourceManager.GetString("ZafeLockEmailUpdateOTP", resourceCulture);
            }
        }
    }
}
