# Generated by Django 4.2.16 on 2025-05-29 07:27

import concurrency.fields
import data.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMigrationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("task", models.CharField(max_length=500)),
                ("execution_version", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("FAILED", "FAILED"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default=data.constants.DataMigrationStatus["IN_PROGRESS"],
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=["task", "execution_version"], name="unique_task_version"
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["task", "execution_version"], name="idx_task_version"
                    ),
                ],
            },
        ),
    ]
