namespace Resido.Model.TTLockDTO.RequestDTO.LockRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class RenameLockRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// New lock alias (name).
        /// </summary>
        public string LockAlias { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockRenameLockRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public string LockAlias { get; set; }
        public string AccessToken { get; set; }
    }

}
