# Generated by Django 4.2.16 on 2025-10-30 10:09

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("task_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "object_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            (
                                "PROCESS_BILL_REFUND_REQUEST",
                                "PROCESS_BILL_REFUND_REQUEST",
                            ),
                            (
                                "TRANSACTIONS_RECONCILIATION",
                                "TRANSACTIONS_RECONCILIATION",
                            ),
                            ("VISIT_TYPE_ASSIGNMENT", "VISIT_TYPE_ASSIGNMENT"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADHOC_VIA_API", "ADHOC_VIA_API"),
                            ("PERIODIC", "PERIODIC"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                            ("CANCELED", "CANCELED"),
                            ("RETRYING", "RETRYING"),
                            ("TIMED_OUT", "TIMED_OUT"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=50,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("report", models.JSONField(blank=True, null=True)),
                ("error_code", models.IntegerField(blank=True, null=True)),
                ("error_body", models.JSONField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["object_id", "process_type", "status"],
                        name="idx_process_lookup",
                    ),
                ],
            },
        ),
    ]
