from django.urls import re_path

import maintenance.apiviews

urlpatterns = (
    re_path(
        r"^api/v1/service-providers$",
        maintenance.apiviews.ServiceProviderListCreateView.as_view(),
        name="service-providers_list_create",
    ),
    re_path(
        r"^api/v1/service-providers/(?P<pk>[0-9a-zA-Z\-]+)$",
        maintenance.apiviews.ServiceProviderDetailUpdateView.as_view(),
        name="service-providers_detail_update",
    ),
    re_path(
        r"^api/v1/service-providers-count$",
        maintenance.apiviews.ServiceProviderCountAPIView.as_view(),
        name="service-providers_count",
    ),
    re_path(
        r"^api/v1/service-provider-phones$",
        maintenance.apiviews.ServiceProviderPhoneListView.as_view(),
        name="service-provider-phones",
    ),
    re_path(
        r"^api/v1/service-provider-documents$",
        maintenance.apiviews.ServiceProviderDocumentListCreateView.as_view(),
        name="service-provider-documents_list_create",
    ),
    re_path(
        r"^api/v1/service-provider-documents/(?P<pk>[0-9a-zA-Z\-]+)$",
        maintenance.apiviews.ServiceProviderDocumentDetailUpdateView.as_view(),
        name="service-provider-documents_detail_update",
    ),
    re_path(
        r"^api/v1/service-provider-reviews$",
        maintenance.apiviews.ServiceProviderReviewListCreateView.as_view(),
        name="service-provider-reviews_list_create",
    ),
    re_path(
        r"^api/v1/maintenance-count$",
        maintenance.apiviews.MaintenanceCountAPIView.as_view(),
        name="maintenance_count",
    ),
    re_path(
        r"^api/v1/maintenance$",
        maintenance.apiviews.MaintenancetListCreateView.as_view(),
        name="maintenance_list_create",
    ),
    re_path(
        r"^api/v1/maintenance/(?P<pk>[0-9a-zA-Z\-]+)$",
        maintenance.apiviews.MaintenanceDetailUpdateView.as_view(),
        name="maintenance_detail_update",
    ),
    re_path(
        r"^api/v1/maintenance/(?P<pk>[0-9a-zA-Z\-]+)/status$",
        maintenance.apiviews.MaintenanceStatusUpdateView.as_view(),
        name="maintenance_status_update",
    ),
    re_path(
        r"^api/v1/maintenance/(?P<pk>[0-9a-zA-Z\-]+)/assign$",
        maintenance.apiviews.MaintenanceAssignView.as_view(),
        name="maintenance_assign",
    ),
    re_path(
        r"^api/v1/maintenance/(?P<pk>[0-9a-zA-Z\-]+)/priority$",
        maintenance.apiviews.MaintenancePriorityUpdateView.as_view(),
        name="maintenance_priority_update",
    ),
)
