# Generated by Django 4.2.16 on 2025-05-20 17:18

import assets.utils
import concurrency.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("image", "image"), ("doc", "doc")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=assets.utils.PathAndRename("assets")),
                ),
                ("filename", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
