"""
Django settings for resido project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import platform
import dj_database_url
import os
from pathlib import Path
import datetime
from dotenv import load_dotenv

from common.constants import LOCAL_ENVIRONMENT, TEST_ENVIRONMENT
from hb_core.constants import TenancyModel
from helixauth.constants import AccessLevel

# from hb_geo.constants import COUNTRY_STATE_MIGRATION_TASK_LIST
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p9z7$(l)r8-f%#5h=+g=(k9(xna7k48+=y_*l7lnaud8t0+wer"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http:\/\/localhost:*([0-9]+)?$",
    r"^https:\/\/localhost:*([0-9]+)?$",
]
CSRF_TRUSTED_ORIGINS = [
    "https://*.helixbeat.com",
    "http://*.helixbeat.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

SHARED_APPS = [
    "debug_toolbar",
    "django_tenants",  # mandatory
    "common",  # you must list the app where your tenant model resides in
    "helixauth",
    "assets",
    "django.contrib.contenttypes",
    "rest_framework_swagger",
    "drf_yasg",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.gis",
    "waffle",
    "rest_framework",
    "rest_framework.authtoken",
    "django_celery_beat",
    "storages",
    "hb_core",
    "hb_geo",
    "enums",
    "customer_backend",
    "subscriptions",
    "s2s_auth",
]

TENANT_APPS = [
    # The following Django contrib apps must be in TENANT_APPS
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework.authtoken",
    "locations",
    "lookup",
    "staff",
    "residents",
    "helixauth",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "notifications",
    "data",
    "django_filters",
    "payments",
    "storages",
    "drf_yasg",
    "assets",
    "djmoney",
    "external",
    "waffle",
    "meetings",
    "audit",
    "dm",
    "analytics",
    "processflow",
    "scheduling",
    "connecthub",
    "lease",
    "digitalforms",
    "maintenance",
    "customer_backend",
    "s2s_auth",
    "bookings",
]

JWT_AUTH = {
    "JWT_VERIFY": True,
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=3600),
    "JWT_AUTH_HEADER_PREFIX": "Bearer",
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(seconds=3600),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "ALGORITHM": "RS256",
}

OAUTH2_PROVIDER = {
    "SCOPES": {
        "read": "Read scope",
        "write": "Write scope",
        "groups": "Access to your groups",
    },
    "OAUTH2_BACKEND_CLASS": "oauth2_provider.oauth2_backends.JSONOAuthLibCore",
}

AUTH_USER_MODEL = "helixauth.HelixUser"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Route tenant_launch tasks to the default celery queue
CELERY_TASK_ROUTES = {
    "customer_backend.managers.runner.tenant_launch.process": {"queue": "celery"},
}


CUSTOMER_BACKEND_SETTINGS = {
    "RLA": {
        "STAFF_ACCESS_LEVEL_RELATION_CONFIG": {
            AccessLevel.Customer.value: [
                {
                    "field_name": "customers",
                    "relation_type": "m2m",
                    "model": "locations.Customer",
                    "path_to_compare": "path_to_customer",
                    "related_name": "staff_customers",
                    "relative_path_suffix": None,
                    "optional": True,
                },
                {
                    "field_name": "customers",
                    "relation_type": "m2m",
                    "model": "locations.Customer",
                    "path_to_compare": "path_to_location",
                    "related_name": "staff_customers",
                    "relative_path_suffix": "__property__location",
                    "optional": True,
                },
            ],
            AccessLevel.Property.value: [
                {
                    "field_name": "properties",
                    "relation_type": "m2m",
                    "model": "locations.Property",
                    "path_to_compare": "path_to_property",
                    "related_name": "properties",
                    "relative_path_suffix": None,
                    "optional": True,
                },
                {
                    "field_name": "properties",
                    "relation_type": "m2m",
                    "model": "locations.Property",
                    "path_to_compare": "path_to_location",
                    "related_name": "properties",
                    "relative_path_suffix": "__location",
                    "optional": True,
                },
            ],
            AccessLevel.Location.value: [
                {
                    "field_name": "locations",
                    "relation_type": "m2m",
                    "model": "locations.Location",
                    "related_name": "staff_locations",
                    "path_to_compare": "path_to_location",
                    "relative_path_suffix": None,
                    "optional": True,
                }
            ],
            AccessLevel.Building.value: [
                {
                    "field_name": "buildings",
                    "relation_type": "m2m",
                    "model": "locations.Building",
                    "related_name": "staff_buildings",
                    "path_to_compare": "path_to_location",
                    "relative_path_suffix": "__location",
                    "optional": True,
                }
            ],
            AccessLevel.Floor.value: [
                {
                    "field_name": "floors",
                    "relation_type": "m2m",
                    "model": "locations.Floor",
                    "related_name": "staff_floors",
                    "path_to_compare": "path_to_location",
                    "relative_path_suffix": "__building__location",
                    "optional": True,
                }
            ],
            AccessLevel.Unit.value: [
                {
                    "field_name": "units",
                    "relation_type": "m2m",
                    "model": "locations.Unit",
                    "related_name": "staff_units",
                    "path_to_compare": "path_to_location",
                    "relative_path_suffix": "__floor__building__location",
                    "optional": True,
                }
            ],
        },
        "USER_ACCESS_LEVEL_RELATION_CONFIG": None,
        "MODULES_YML_DATA_PATH": None,
        "MODULES_COMP_YML_DATA_PATH": None,
        "SUBMODULES_YML_DATA_PATH": None,
        "ROLES_CSV_DATA_PATH": "data/rla/user_roles.csv",
        "ROLES_MODULE_PERM_MAP_CSV_DATA_PATH": "data/rla/permissions/modules_permissions_mapping.csv",
        "ROLES_SUB_MODULE_PERM_YML_DATA_PATH": None,
        "PATH_TO_COMPARE_FOR_CONSUMER": "path_to_resident_id",
        "MODULE_MIG_TASK_VERSION": 1,
        "PERM_MIG_TASK_VERSION": 1,
    },
    "BACKEND": {
        "DEFAULT_MODEL_MANAGER_CLASS_PATH": "common.managers.model.generic.GenericModelManager",
        "STAFF_MANAGER_CLASS_PATH": "staff.managers.helixstaff.HelixStaffManager",
        "ENTITY_MODEL": "locations.Property",
        "CUSTOMER_MODEL": "locations.Customer",
        "LOCATION_MODEL": "locations.Location",
        "LOCATION_ENTITY_FIELD_NAME": "property",
        "LOCATION_ENTITY_FIELD_RELATED_NAME": "location",
        "ENTITY_CUSTOMER_FIELD_RELATED_NAME": "property",
        "ACCESS_LEVEL_ENUM_CLASS": AccessLevel,
        "ACCESS_LEVEL_RANK_MAP": {
            # Access Level to Rank Map. Lower the Rank Value, Higher the Rank is
            AccessLevel.Admin.value: 0,
            AccessLevel.Customer.value: 1,
            AccessLevel.Property.value: 2,
            AccessLevel.Location.value: 3,
            AccessLevel.Building.value: 4,
            AccessLevel.Floor.value: 5,
            AccessLevel.Unit.value: 6,
        },
        "STAFF_MODEL": "staff.HelixStaff",
        "CONSUMER_MODEL": "residents.Resident",
        "ACCESS_LEVEL_ASSIGNMENT_LEVEL_MAP": {
            # Maps staff access levels to paths for filtering consumers (residents)
            # Format: staff_access_level -> {consumer_assignment_level -> path_from_consumer}
            AccessLevel.Customer.value: {
                AccessLevel.Location.value: "leases__unit__floor__building__location__property__customer",
            },
            AccessLevel.Property.value: {
                AccessLevel.Location.value: "leases__unit__floor__building__location__property",
            },
            AccessLevel.Location.value: {
                AccessLevel.Location.value: "leases__unit__floor__building__location",
            },
            AccessLevel.Building.value: {
                AccessLevel.Location.value: "leases__unit__floor__building",
            },
            AccessLevel.Floor.value: {
                AccessLevel.Location.value: "leases__unit__floor",
            },
            AccessLevel.Unit.value: {
                AccessLevel.Location.value: "leases__unit",
            },
        },
        "RELATED_NAME_OF_USER_IN_CONSUMER": "resident",
        "TENANT_SUBSCRIPTION_MODEL": None,
        "TENANT_DEFAULT_DATA": {"service_name": "tenant"},
        "TENANT_POST_LAUNCH_HOOKS": [
            "common.hooks.customer_onboarding.CustomerOnboardingManager",
            "subscriptions.managers.subscription.TenantSubscriptionManager",
        ],
        "TENANT_POST_DM_HOOKS": [
            "common.hooks.dm_notification.CustomerDMNotificationManager",
        ],
    },
}

TN_AUTH_PUBLIC_KEY_PATH = (
    os.getenv("TN_AUTH_PUBLIC_KEY_PATH")
    if os.getenv("TN_AUTH_PUBLIC_KEY_PATH")
    and os.getenv("TN_AUTH_PUBLIC_KEY_PATH") != "None"
    else "./keys/tn_public_key.pem"
)
TN_AUTH_PRIVATE_KEY_PATH = (
    os.getenv("TN_AUTH_PRIVATE_KEY_PATH")
    if os.getenv("TN_AUTH_PRIVATE_KEY_PATH")
    and os.getenv("TN_AUTH_PRIVATE_KEY_PATH") != "None"
    else "./keys/tn_private_key.pem"
)

if os.getenv("ENVIRONMENT", LOCAL_ENVIRONMENT) == TEST_ENVIRONMENT:
    TN_AUTH_PUBLIC_KEY = None
    TN_AUTH_PRIVATE_KEY = None
else:
    TN_AUTH_PUBLIC_KEY = open(TN_AUTH_PUBLIC_KEY_PATH).read()
    TN_AUTH_PRIVATE_KEY = open(TN_AUTH_PRIVATE_KEY_PATH).read()

SERVICES_KEY = os.getenv("SERVICES_KEY", "e42f6a6daffc1b7bd9b3138a8eb435d9f7a5bf43")
SERVICES_URL = os.getenv("SERVICES_URL")
ADDRESS_URL = os.getenv("ADDRESS_URL")

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
SITE_ID = 1

TENANT_MODEL = "common.HealthCareCustomer"
TENANT_DOMAIN_MODEL = "common.Domain"

TENANCY_MODEL = TenancyModel.MULTI_TENANT.value
SERVICE_NAME = "TENANT"

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "log_request_id.middleware.RequestIDMiddleware",
    "common.middlewares.request.RequestLoggingMiddleware",
    # "silk.middleware.SilkyMiddleware",
    "common.middlewares.tenant.StandardTenantMiddleware",
    "customer_backend.middlewares.tenant_launch.TenantLaunchMiddleware",
    "concurrency.middleware.ConcurrencyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "waffle.middleware.WaffleMiddleware",
]

DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.history.HistoryPanel",
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
]

CONCURRENCY_HANDLER409 = "common.response.handle_conflict"
CONCURRENCY_POLICY = 2  # CONCURRENCY_LIST_EDITABLE_POLICY_ABORT_ALL
WAFFLE_CREATE_MISSING_SWITCHES = True
WAFFLE_SWITCH_DEFAULT = False

ROOT_URLCONF = "resido.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "payments/data/bill",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "resido.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {}
DATABASES["default"] = dj_database_url.config(default=os.getenv("DATABASE_URL"))
DATABASES["default"]["ENGINE"] = "django_tenants.postgresql_backend"

for db in DATABASES.values():
    db["ATOMIC_REQUESTS"] = True

if "6432" in os.getenv("DATABASE_URL"):
    DATABASES["default"]["CONN_MAX_AGE"] = 0


DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)
ORIGINAL_BACKEND = "resido.database"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 6},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django_advanced_password_validation.advanced_password_validation.ContainsUppercaseValidator"
    },
    {
        "NAME": "django_advanced_password_validation.advanced_password_validation.ContainsDigitsValidator"
    },
    {
        "NAME": "django_advanced_password_validation.advanced_password_validation.ContainsSpecialCharactersValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER")
AZURE_LOCATION = os.getenv("AZURE_LOCATION")
AZURE_URL_EXPIRATION_SECS = 300


BASE_DIR = os.path.dirname(os.path.dirname(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
ROOT_DIR = os.path.join(BASE_DIR, ".")
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK_RENDERER_CLASSES = ["rest_framework.renderers.JSONRenderer"]


# rest_framework.renderers.BrowsableAPIRenderer
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "helixauth.authentication.kc.KeyCloakAuthentication",
    ),
    #'DEFAULT_THROTTLE_CLASSES': (
    #    # This allows us to add global anon user limits
    #    'core.throttling.AnonRateThrottle',
    #    # # This allows us to add global per user limits
    #    'core.throttling.UserRateThrottle',
    #    # # This allows us to add a per API limits in addition to global limits
    #    'core.throttling.ScopedRateThrottle',
    # ),
    #'DEFAULT_THROTTLE_RATES': {
    #    # Anon users are used only for a few things like login/password reset/setup
    #    # So a limit of 100/day should be enough
    #    'anon': '100/day',
    #    # Portal users can make a siginficant number of calls
    #    # so we set their limit at 10K/day
    #    'user': '10000/day',
    #    # The limits are in addittion to global limits
    #    'members_create': '10/minute',
    #    'register_sponsor': '10/minute',
    #    'member_register_number': '10/minute',
    # },
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "COERCE_DECIMAL_TO_STRING": False,
    #'EXCEPTION_HANDLER': 'core.exceptions.gravty_exception_handler',
    "DEFAULT_RENDERER_CLASSES": REST_FRAMEWORK_RENDERER_CLASSES,
    "EXCEPTION_HANDLER": "common.exception.standard_api_exception_handler",
}

USE_X_FORWARDED_HOST = True

LOGIN_REDIRECT_URL = "/logged_in/"
LOGIN_URL = "/login/"

if platform.system() == "Darwin":
    # For Mac OS
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH")
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH")

# # Removed above lines as its causing issues in unbuntu. Donot uncomment them before testing

if platform.system() == "Windows":
    # for windows
    # replace with the path in your system
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH")
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH")
    PROJ_LIBRARY_PATH = os.getenv("PROJ_LIBRARY_PATH")

INTERNAL_IPS = ["127.0.0.1"]

# LOGGING Settings
GENERATE_REQUEST_ID_IF_NOT_IN_HEADER = True
APPLICATION_LOG_LEVEL = "DEBUG" if os.getenv("ENVIRONMENT") != "PROD" else "INFO"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "filters": {"request_id": {"()": "log_request_id.filters.RequestIDFilter"}},
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s]- %(message)s"},
        "json": {
            "()": "common.utils.logging.StandardJSONLogFormatter",
        },
    },
    "handlers": {
        "console": {
            "level": APPLICATION_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id"],
        },
    },
    "loggers": {
        "hb_logger": {
            "handlers": ["console"],
            "level": APPLICATION_LOG_LEVEL,
            "propagate": True,
        },
    },
}

BASE_REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": BASE_REDIS_URL,
        "KEY_FUNCTION": "common.managers.cache.key.get_pulse_cache_key",
    }
}

CURRENCIES = ("USD", "INR")
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOCAL_DM_REGISTRY = [
    # LIST OF LOCAL DATA MIGRATION TASKS
]
# DATA_MIGRATION_REGISTRY = LOCAL_DM_REGISTRY + COUNTRY_STATE_MIGRATION_TASK_LIST

# Backend Core Settings
STAFF_MODEL = "staff.HelixStaff"
