namespace Resido.Model.TTLockDTO.RequestDTO.CardRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class ChangeCardPeriodRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Card ID to change (from AddCard response).
        /// </summary>
        public int CardId { get; set; }

        /// <summary>
        /// Start time when card becomes valid (timestamp in ms).
        /// </summary>
        public long StartDate { get; set; }

        /// <summary>
        /// End time when card expires (timestamp in ms).
        /// </summary>
        public long EndDate { get; set; }

        /// <summary>
        /// Optional: recurring time period for cyclic cards.
        /// </summary>
        public List<CyclicConfigDTO>? CyclicConfig { get; set; }

        /// <summary>
        /// Method of change (1 = Bluetooth, 2 = Cloud).
        /// </summary>
        public AddType ChangeType { get; set; } = AddType.Cloud;
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockChangeCardPeriodRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int CardId { get; set; }
        public long StartDate { get; set; }
        public long EndDate { get; set; }
        public List<CyclicConfigDTO>? CyclicConfig { get; set; }
        public int ChangeType { get; set; }
        public string AccessToken { get; set; }
    }

}
