namespace Resido.Model.TTLockDTO.RequestDTO.CardRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class DeleteCardRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Card ID to delete (from AddCard response).
        /// </summary>
        public int CardId { get; set; }

        /// <summary>
        /// Method of deletion (1 = Bluetooth, 2 = Cloud).
        /// </summary>
        public AddType DeleteType { get; set; } = AddType.Cloud;
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockDeleteCardRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int CardId { get; set; }
        public int DeleteType { get; set; }
        public string AccessToken { get; set; }
    }

}
