namespace Resido.Model.TTLockDTO.RequestDTO.CardRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class ListIdentityCardRequestDTO: PagingRequest
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Optional: search keywords (fuzzy by card name).
        /// </summary>
        public string? SearchStr { get; set; }

        /// <summary>
        /// Sort order: 0 = by name, 1 = reverse order by time, 2 = reverse order by name.
        /// </summary>
        public int OrderBy { get; set; } = 1;
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockListIdentityCardRequestDTO : BaseRequestDTO, IAccessTokenRequest, IPagingRequest
    {
        public int LockId { get; set; }
        public string? SearchStr { get; set; }
        public int PageNo { get; set; }
        public int PageSize { get; set; }
        public int OrderBy { get; set; }
        public string AccessToken { get; set; }
    }

}
