namespace Resido.Model.TTLockDTO.RequestDTO.CardRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class RenameCardRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Card ID to rename (from AddCard response).
        /// </summary>
        public int CardId { get; set; }

        /// <summary>
        /// New card name.
        /// </summary>
        public string CardName { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockRenameCardRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int CardId { get; set; }
        public string CardName { get; set; }
        public string AccessToken { get; set; }
    }
}
