from django.urls import re_path

from analytics.apiviews.billing import (
    FinancialSummaryAPIView,
    ServiceCategoryAmountDistributionAPIView,
    ServiceTypeAmountDistributionAPIView,
    PaymentStatsAPIView,
    BillStatsAPIView,
    CombinedFinancialMetricsAPIView,
    BillProcessStatsAPIView,
    PaymentMethodStatsAPIView,
    InsuranceSelfpayComparisonAPIView,
    PaymentTrendAPIView,
)
from analytics.apiviews.dashboard import (
    OutstandingBalanceAPIView,
    NewLeasesSignedAPIView,
    OpenWorkOrdersCardAPIView,
    SupportTicketsRaisedAPIView,
    VacancyRateAPIView,
    OccupancyRateAPIView,
    RevenueLeakageAPIView,
    LeaseRenewalRateAPIView,
    LeaseDocumentStatusAPIView,
    PaymentsCollectedAPIView,
    PaymentSuccessRateAPIView,
    RentCollectionRateAPIView,
    AgedReceivablesAPIView,
    ExpenseBreakdownAPIView,
    WorkOrdersStatsAPIView,
    RecurringMaintenanceTasksAPIView,
    MaintenanceCostTrendsAPIView,
    RenterSatisfactionScoreAPIView,
    TopComplaintsLoggedAPIView,
    InsuranceExpiryAlertsAPIView,
    InspectionReportsAPIView,
    UnitTypeDistributionAPIView,
    TotalUnitsByPropertyAPIView,
    AverageRentPerUnitTypeAPIView,
    UpcomingVacanciesAPIView,
    PMRvsCashCollectedAPIView,
    MoveInsVsMoveOutsAPIView,
    DelinquencyRateAPIView,
    UnitTurnoverTimeAPIView,
    TicketsByCategoryTrendAPIView,
    AvgTicketResolutionTimeAPIView,
    SupportTicketsRaisedLineChartAPIView,
    SLAComplaintsByMonthAPIView,
    TicketResolutionSLAComplaintsAPIView,
)


urlpatterns = [
    re_path(
        r"api/v1/analytics/financial-summary$",
        FinancialSummaryAPIView.as_view(),
        name="list_financial_summary",
    ),
    re_path(
        r"api/v1/analytics/service-category-distribution$",
        ServiceCategoryAmountDistributionAPIView.as_view(),
        name="service_category_distribution",
    ),
    re_path(
        r"api/v1/analytics/service-type-distribution$",
        ServiceTypeAmountDistributionAPIView.as_view(),
        name="service_type_distribution",
    ),
    re_path(
        r"api/v1/analytics/payment-stats$",
        PaymentStatsAPIView.as_view(),
        name="payment_stats",
    ),
    re_path(
        r"api/v1/analytics/bill-stats$",
        BillStatsAPIView.as_view(),
        name="bill_stats",
    ),
    re_path(
        r"api/v1/analytics/combined-financial-metrics$",
        CombinedFinancialMetricsAPIView.as_view(),
        name="combined_financial_metrics",
    ),
    re_path(
        r"api/v1/bill-process-stats$",
        BillProcessStatsAPIView.as_view(),
        name="bill_process_stats",
    ),
    re_path(
        r"api/v1/analytics/payment-method-stats$",
        PaymentMethodStatsAPIView.as_view(),
        name="payment_reason_stats",
    ),
    re_path(
        r"api/v1/analytics/insurance-selfpay-comparison$",
        InsuranceSelfpayComparisonAPIView.as_view(),
        name="insurance_selfpay_comparison",
    ),
    re_path(
        r"api/v1/analytics/payment-trend$",
        PaymentTrendAPIView.as_view(),
        name="payment-trend",
    ),
    re_path(
        r"api/v1/analytics/dashboard/outstanding-balance$",
        OutstandingBalanceAPIView.as_view(),
        name="outstanding_balance",
    ),
    re_path(
        r"api/v1/analytics/dashboard/new-leases-signed$",
        NewLeasesSignedAPIView.as_view(),
        name="new_leases_signed",
    ),
    re_path(
        r"api/v1/analytics/dashboard/open-work-orders$",
        OpenWorkOrdersCardAPIView.as_view(),
        name="open_work_orders",
    ),
    re_path(
        r"api/v1/analytics/dashboard/support-tickets-raised$",
        SupportTicketsRaisedAPIView.as_view(),
        name="support_tickets_raised",
    ),
    re_path(
        r"api/v1/analytics/dashboard/vacancy-rate$",
        VacancyRateAPIView.as_view(),
        name="vacancy_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/occupancy-rate$",
        OccupancyRateAPIView.as_view(),
        name="occupancy_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/revenue-leakage$",
        RevenueLeakageAPIView.as_view(),
        name="revenue_leakage",
    ),
    re_path(
        r"api/v1/analytics/dashboard/lease-renewal-rate$",
        LeaseRenewalRateAPIView.as_view(),
        name="lease_renewal_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/lease-document-status$",
        LeaseDocumentStatusAPIView.as_view(),
        name="lease_document_status",
    ),
    re_path(
        r"api/v1/analytics/dashboard/payments-collected$",
        PaymentsCollectedAPIView.as_view(),
        name="payments_collected",
    ),
    re_path(
        r"api/v1/analytics/dashboard/payment-success-rate$",
        PaymentSuccessRateAPIView.as_view(),
        name="payment_success_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/rent-collection-rate$",
        RentCollectionRateAPIView.as_view(),
        name="rent_collection_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/aged-receivables$",
        AgedReceivablesAPIView.as_view(),
        name="aged_receivables",
    ),
    re_path(
        r"api/v1/analytics/dashboard/expense-breakdown$",
        ExpenseBreakdownAPIView.as_view(),
        name="expense_breakdown",
    ),
    re_path(
        r"api/v1/analytics/dashboard/work-orders$",
        WorkOrdersStatsAPIView.as_view(),
        name="work_orders",
    ),
    re_path(
        r"api/v1/analytics/dashboard/recurring-maintenance-tasks$",
        RecurringMaintenanceTasksAPIView.as_view(),
        name="recurring_maintenance_tasks",
    ),
    re_path(
        r"api/v1/analytics/dashboard/maintenance-cost-trends$",
        MaintenanceCostTrendsAPIView.as_view(),
        name="maintenance_cost_trends",
    ),
    re_path(
        r"api/v1/analytics/dashboard/renter-satisfaction-score$",
        RenterSatisfactionScoreAPIView.as_view(),
        name="renter_satisfaction_score",
    ),
    re_path(
        r"api/v1/analytics/dashboard/top-complaints-logged$",
        TopComplaintsLoggedAPIView.as_view(),
        name="top_complaints_logged",
    ),
    re_path(
        r"api/v1/analytics/dashboard/insurance-expiry-alerts$",
        InsuranceExpiryAlertsAPIView.as_view(),
        name="insurance_expiry_alerts",
    ),
    re_path(
        r"api/v1/analytics/dashboard/inspection-reports$",
        InspectionReportsAPIView.as_view(),
        name="inspection_reports",
    ),
    re_path(
        r"api/v1/analytics/dashboard/unit-type-distribution$",
        UnitTypeDistributionAPIView.as_view(),
        name="unit_type_distribution",
    ),
    re_path(
        r"api/v1/analytics/dashboard/total-units-by-property$",
        TotalUnitsByPropertyAPIView.as_view(),
        name="total_units_by_property",
    ),
    re_path(
        r"api/v1/analytics/dashboard/average-rent-per-unit-type$",
        AverageRentPerUnitTypeAPIView.as_view(),
        name="average_rent_per_unit_type",
    ),
    re_path(
        r"api/v1/analytics/dashboard/upcoming-vacancies$",
        UpcomingVacanciesAPIView.as_view(),
        name="upcoming_vacancies",
    ),
    re_path(
        r"api/v1/analytics/dashboard/pmr-vs-cash-collected$",
        PMRvsCashCollectedAPIView.as_view(),
        name="pmr_vs_cash_collected",
    ),
    re_path(
        r"api/v1/analytics/dashboard/move-ins-vs-move-outs$",
        MoveInsVsMoveOutsAPIView.as_view(),
        name="move_ins_vs_move_outs",
    ),
    re_path(
        r"api/v1/analytics/dashboard/delinquency-rate$",
        DelinquencyRateAPIView.as_view(),
        name="delinquency_rate",
    ),
    re_path(
        r"api/v1/analytics/dashboard/unit-turnover-time$",
        UnitTurnoverTimeAPIView.as_view(),
        name="unit_turnover_time",
    ),
    re_path(
        r"api/v1/analytics/dashboard/tickets-by-category-trend$",
        TicketsByCategoryTrendAPIView.as_view(),
        name="tickets_by_category_trend",
    ),
    re_path(
        r"api/v1/analytics/dashboard/avg-ticket-resolution-time$",
        AvgTicketResolutionTimeAPIView.as_view(),
        name="avg_ticket_resolution_time",
    ),
    re_path(
        r"api/v1/analytics/dashboard/line-chart-support-tickets-raised$",
        SupportTicketsRaisedLineChartAPIView.as_view(),
        name="line_chart_support_tickets_raised",
    ),
    re_path(
        r"api/v1/analytics/dashboard/sla-compliance-by-month$",
        SLAComplaintsByMonthAPIView.as_view(),
        name="sla_compliance_by_month",
    ),
    re_path(
        r"api/v1/analytics/dashboard/ticket-resolution-sla-compliance$",
        TicketResolutionSLAComplaintsAPIView.as_view(),
        name="ticket_resolution_sla_compliance",
    ),
]
