from django.urls import re_path

import locations.apiviews

urlpatterns = (
    re_path(
        r"^api/v1/locations$",
        locations.apiviews.LocationListCreate.as_view(),
        name="centers_list",
    ),
    re_path(
        r"^api/v1/locations/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.LocationDetail.as_view(),
        name="centers_detail",
    ),
    re_path(
        r"^api/v1/locations-trimmed$",
        locations.apiviews.LocationTrimmedView.as_view(),
        name="centers_list",
    ),
    re_path(
        r"^api/v1/properties$",
        locations.apiviews.PropertyList.as_view(),
        name="health_center_list",
    ),
    re_path(
        r"^api/v1/properties/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.PropertyDetail.as_view(),
        name="health_center_detail",
    ),
    re_path(
        r"^api/v1/customers$",
        locations.apiviews.CustomersListCreate.as_view(),
        name="customer_list_create",
    ),
    re_path(
        r"^api/v1/customers/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.CustomersDetailUpdate.as_view(),
        name="customer_detail_update",
    ),
    re_path(
        r"^api/v1/customers-count$",
        locations.apiviews.CustomerCountAPIView.as_view(),
        name="customer_count",
    ),
    re_path(
        r"^api/v1/buildings$",
        locations.apiviews.BuildingListCreateAPIView.as_view(),
        name="buildings_list_create",
    ),
    re_path(
        r"^api/v1/buildings/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.BuildingDetailUpdate.as_view(),
        name="buildings_detail_update",
    ),
    re_path(
        r"^api/v1/floors$",
        locations.apiviews.FloorListCreateAPIView.as_view(),
        name="floors_list_create",
    ),
    re_path(
        r"^api/v1/floors/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.FloorDetailUpdate.as_view(),
        name="floors_detail_update",
    ),
    re_path(
        r"^api/v1/units$",
        locations.apiviews.UnitListCreateAPIView.as_view(),
        name="units_list_create",
    ),
    re_path(
        r"^api/v1/units/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.UnitDetailUpdate.as_view(),
        name="units_detail_update",
    ),
    re_path(
        r"^api/v1/amenities$",
        locations.apiviews.AmenityListCreateAPIView.as_view(),
        name="amenities_list_create",
    ),
    re_path(
        r"^api/v1/amenities/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.AmenityDetailUpdate.as_view(),
        name="amenities_detail_update",
    ),
    re_path(
        r"^api/v1/parking-levels$",
        locations.apiviews.ParkingLevelListCreateAPIView.as_view(),
        name="parking_levels_list_create",
    ),
    re_path(
        r"^api/v1/parking-levels/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.ParkingLevelDetailUpdate.as_view(),
        name="parking_levels_detail_update",
    ),
    re_path(
        r"^api/v1/parking-level-count$",
        locations.apiviews.ParkingLevelCountAPIView.as_view(),
        name="parking_level_count",
    ),
    re_path(
        r"^api/v1/parking-zones/bulk-create$",
        locations.apiviews.ParkingZoneBulkCreateAPIView.as_view(),
        name="parking_zone_bulk_create",
    ),
    re_path(
        r"^api/v1/parking-zones$",
        locations.apiviews.ParkingZoneListCreateAPIView.as_view(),
        name="parking_zones_list_create",
    ),
    re_path(
        r"^api/v1/parking-zones/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.ParkingZoneDetailUpdate.as_view(),
        name="parking_zones_detail_update",
    ),
    re_path(
        r"^api/v1/parking-slots/bulk-create$",
        locations.apiviews.ParkingSlotBulkCreateAPIView.as_view(),
        name="parking_slots_bulk_create",
    ),
    re_path(
        r"^api/v1/parking-slots$",
        locations.apiviews.ParkingSlotListCreateAPIView.as_view(),
        name="parking_slots_list_create",
    ),
    re_path(
        r"^api/v1/parking-slots/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.ParkingSlotDetailUpdate.as_view(),
        name="parking_slots_detail_update",
    ),
    re_path(
        r"^api/v1/parking-slot-count$",
        locations.apiviews.ParkingSlotCountAPIView.as_view(),
        name="parking_slot_count",
    ),
    re_path(
        r"^api/v1/properties/(?P<pk>[0-9a-zA-Z\-]+)/saved-tabs-status$",
        locations.apiviews.PropertySavedTabsStatus.as_view(),
        name="property_saved_tabs_status",
    ),
    re_path(
        r"^api/v1/properties/(?P<pk>[0-9a-zA-Z\-]+)/entity-count$",
        locations.apiviews.PropertyEntityCountAPIView.as_view(),
        name="property_entity_count",
    ),
    re_path(
        r"^api/v1/my-properties$",
        locations.apiviews.MyPropertiesListAPIView.as_view(),
        name="my_properties_list",
    ),
    re_path(
        r"^api/v1/my-properties/(?P<pk>[0-9a-zA-Z\-]+)$",
        locations.apiviews.MyPropertiesDetailAPIView.as_view(),
        name="my_properties_detail",
    ),
)
