from django.urls import re_path
import residents.apiviews

urlpatterns = (
    re_path(
        r"^api/v1/residents$",
        residents.apiviews.ResidentListCreateAPIView.as_view(),
        name="residents_list_create",
    ),
    re_path(
        r"^api/v1/residents-count$",
        residents.apiviews.ResidentCountAPIView.as_view(),
        name="residents_count",
    ),
    re_path(
        r"^api/v1/resident-addressess$",
        residents.apiviews.ResidentAddressListCreateAPIView.as_view(),
        name="resident_address_list_create",
    ),
    re_path(
        r"^api/v1/resident-addressess/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentAddressDetail.as_view(),
        name="resident_address_edit",
    ),
    re_path(
        r"^api/v1/resident-co-occupants$",
        residents.apiviews.ResidentCoOccupantsListCreateAPIView.as_view(),
        name="resident_co_occupant_list_create",
    ),
    re_path(
        r"^api/v1/resident-co-occupants/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentCoOccupantsDetail.as_view(),
        name="resident_co_occupant_edit",
    ),
    re_path(
        r"^api/v1/resident-financial-guarantors$",
        residents.apiviews.ResidentFinancialGurantorsListCreateAPIView.as_view(),
        name="resident_financial_guarantors_list_create",
    ),
    re_path(
        r"^api/v1/resident-financial-guarantors/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentFinancialGurantorsDetail.as_view(),
        name="resident_financial_guarantors_edit",
    ),
    re_path(
        r"^api/v1/residents/family$",
        residents.apiviews.ResidentsFamilyCreateListAPIView.as_view(),
        name="residents_family_list",
    ),
    re_path(
        r"^api/v1/residents/login$",
        residents.apiviews.ResidentLoginAPIView.as_view(),
        name="residents_login",
    ),
    re_path(
        r"^api/v1/residents/refresh-token$",
        residents.apiviews.ResidentRefreshTokenAPIView.as_view(),
        name="residents_refresh_token",
    ),
    re_path(
        r"^api/v1/residents/reset-password$",
        residents.apiviews.ResidentResetPasswordAPIView.as_view(),
        name="residents_reset_password",
    ),
    re_path(
        r"^api/v1/residents/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentDetail.as_view(),
        name="residents_detail",
    ),
    re_path(
        r"^api/v1/address_validation$",
        residents.apiviews.AddressValidation.as_view(),
        name="address_validation",
    ),
    re_path(
        r"^api/v1/emergency-contacts$",
        residents.apiviews.EmergencyContactCreate.as_view(),
        name="emergency_contact_create",
    ),
    re_path(
        r"^api/v1/emergency-contacts/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.EmergencyContactDetail.as_view(),
        name="emergency_contact_detail",
    ),
    re_path(
        r"^api/v1/resident-registered-devices$",
        residents.apiviews.ResidentRegisteredDevicesAPIView.as_view(),
        name="registered_device_list",
    ),
    re_path(
        r"^api/v1/resident-access-logs$",
        residents.apiviews.ResidentAccessLogAPIView.as_view(),
        name="access_logs_list",
    ),
    re_path(
        r"^api/v1/resident-logout-device$",
        residents.apiviews.ResidentLogoutRegisteredDevicesAPIView.as_view(),
        name="logout_registered_device",
    ),
    re_path(
        r"^api/v1/residents/(?P<pk>[0-9a-zA-Z\-]+)/unlock$",
        residents.apiviews.ResidentUnlockAPIView.as_view(),
        name="user_unlock",
    ),
    re_path(
        r"^api/v1/resident-documents$",
        residents.apiviews.ResidentDocumentListCreateAPIView.as_view(),
        name="resident_documents_list_create",
    ),
    re_path(
        r"^api/v1/resident-documents/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentDocumentDetail.as_view(),
        name="resident_documents_edit",
    ),
    re_path(
        r"^api/v1/resident-eviction$",
        residents.apiviews.ResidentEvictionListCreateAPIView.as_view(),
        name="resident_eviction_list_create",
    ),
    re_path(
        r"^api/v1/resident-eviction/(?P<pk>[0-9a-zA-Z\-]+)$",
        residents.apiviews.ResidentEvictionDetail.as_view(),
        name="resident_eviction_edit",
    ),
    re_path(
        r"^api/v1/resident-invitation$",
        residents.apiviews.ResidentInvitationAPIView.as_view(),
        name="resident_eviction_edit",
    ),
    re_path(
        r"^api/v1/residents/(?P<pk>[0-9a-zA-Z\-]+)/rented-properties$",
        residents.apiviews.RenterRentedPropertiesAPIView.as_view(),
        name="renter_rented_properties",
    ),
    re_path(
        r"^api/v1/residents/(?P<pk>[0-9a-zA-Z\-]+)/profile$",
        residents.apiviews.RenterProfileAPIView.as_view(),
        name="renter_profile",
    ),
)
