# from django.urls import re_path

# from scheduling.api.vt import (
#     VisitCategoriesListCreateBulkAPIView,
#     VisitCategoriesRetrieveUpdateAPIView,
#     VisitTypesListCreateBulkAPIView,
#     VisitTypesRetrieveUpdateAPIView,
#     VisitTypeTemplatesListCreateAPIView,
#     VisitTypeTemplatesRetrieveUpdateAPIView,
#     VisitTypeAssignmentRequestListCreateAPIView,
# )
# from scheduling.apiviews import (
#     StaffVisitTypeConfigurationListCreate,
#     StaffEventsListCreateAPIView,
#     StaffEventRetrieveUpdateAPIView,
#     EventOccurrenceUpdatesListCreateAPIView,
#     EventOccurrenceUpdatesRetrieveUpdateAPIView,
#     StaffScheduleAPIView,
#     StaffSlotsPIView,
#     StaffCalendarAPIView,
#     ScheduleTemplatesListCreateAPIView,
#     ScheduleTemplatesRetrieveUpdateAPIView,
#     ScheduleTemplateDetailsListCreateAPIView,
#     LocationScheduleListCreateAPIView,
#     StaffWorkingHourListCreateAPIView,
#     ScheduleTemplateDetailsRetrieveUpdateAPIView,
#     LocationScheduleRetrieveUpdateAPIView,
#     LocationScheduleDetailsListCreateAPIView,
#     LocationScheduleDetailsRetrieveUpdateAPIView,
#     StaffWorkingHourDetailListCreateAPIView,
#     StaffWorkingHourDetailRetrieveUpdateAPIView,
#     VisitTypeCategoriesAPIView,
# )

# urlpatterns = [
#     re_path(
#         r'api/v1/schedule-templates$',
#         ScheduleTemplatesListCreateAPIView.as_view(),
#         name="list_create_schedule_templates",
#     ),
#     re_path(
#         r'api/v1/schedule-templates/(?P<pk>[0-9a-zA-Z\-]+)$',
#         ScheduleTemplatesRetrieveUpdateAPIView.as_view(),
#         name="retrieve_update_schedule_templates",
#     ),
#     re_path(
#         r'api/v1/schedule-template-details$',
#         ScheduleTemplateDetailsListCreateAPIView.as_view(),
#         name="list_create_schedule_template_detail",
#     ),
#     re_path(
#         r'api/v1/schedule-template-details/(?P<pk>[0-9a-zA-Z\-]+)$',
#         ScheduleTemplateDetailsRetrieveUpdateAPIView.as_view(),
#         name="retrieve_update_schedule_template_detail",
#     ),
#     re_path(
#         r'api/v1/location-schedules$',
#         LocationScheduleListCreateAPIView.as_view(),
#         name="list_create_location_schedule",
#     ),
#     re_path(
#         r'api/v1/location-schedules/(?P<pk>[0-9a-zA-Z\-]+)$',
#         LocationScheduleRetrieveUpdateAPIView.as_view(),
#         name="retrieve_update_location_schedule",
#     ),
#     re_path(
#         r'api/v1/location-schedule-details$',
#         LocationScheduleDetailsListCreateAPIView.as_view(),
#         name="list_create_location_schedule_details",
#     ),
#     re_path(
#         r'api/v1/location-schedule-details/(?P<pk>[0-9a-zA-Z\-]+)$',
#         LocationScheduleDetailsRetrieveUpdateAPIView.as_view(),
#         name="retrieve_update_location_schedule_details",
#     ),
#     re_path(
#         r'api/v1/staff-workinghours$',
#         StaffWorkingHourListCreateAPIView.as_view(),
#         name="list_create_staff_workinghours",
#     ),
#     re_path(
#         r'api/v1/staff-workinghour-details$',
#         StaffWorkingHourDetailListCreateAPIView.as_view(),
#         name="list_create_staff_workinghour_details",
#     ),
#     re_path(
#         r'api/v1/staff-workinghour-details/(?P<pk>[0-9a-zA-Z\-]+)$',
#         StaffWorkingHourDetailRetrieveUpdateAPIView.as_view(),
#         name="retrieve_update_staff_workinghour_details",
#     ),
#     re_path(
#         r'api/v1/visit-type-configs$',
#         StaffVisitTypeConfigurationListCreate.as_view(),
#         name="list_create_visit_type_config",
#     ),
#     re_path(
#         r'api/v1/events$',
#         StaffEventsListCreateAPIView.as_view(),
#         name="staff_events_list_create",
#     ),
#     re_path(
#         r'api/v1/events/(?P<pk>[0-9a-zA-Z\-]+)$',
#         StaffEventRetrieveUpdateAPIView.as_view(),
#         name="staff_event_retrieve_update",
#     ),
#     re_path(
#         r'api/v1/event-occurence-updates$',
#         EventOccurrenceUpdatesListCreateAPIView.as_view(),
#         name="staff_event_occurrence_update",
#     ),
#     re_path(
#         r'api/v1/event-occurence-updates/(?P<pk>[0-9a-zA-Z\-]+)$',
#         EventOccurrenceUpdatesRetrieveUpdateAPIView.as_view(),
#         name="staff_event_occurrence_update_retrieve_update",
#     ),
#     re_path(
#         r'api/v1/providers/(?P<staff_id>[0-9a-zA-Z\-]+)/schedules$',
#         StaffScheduleAPIView.as_view(),
#         name="provider_schedule",
#     ),
#     re_path(
#         r'api/v1/providers/(?P<staff_id>[0-9a-zA-Z\-]+)/slots$',
#         StaffSlotsPIView.as_view(),
#         name="provider_available_slots",
#     ),
#     re_path(
#         r'api/v1/providers/(?P<staff_id>[0-9a-zA-Z\-]+)/calendars$',
#         StaffCalendarAPIView.as_view(),
#         name="provider_calendar",
#     ),
#     re_path(
#         r'api/v1/vt-categories$',
#         VisitTypeCategoriesAPIView.as_view(),
#         name="list_vt_categories",
#     ),
#     re_path(
#         r"api/v1/visit-categories$",
#         VisitCategoriesListCreateBulkAPIView.as_view(),
#         name="list_create_visit_categories",
#     ),
#     re_path(
#         r"api/v1/visit-categories/(?P<pk>[0-9a-zA-Z\-]+)$",
#         VisitCategoriesRetrieveUpdateAPIView.as_view(),
#         name="visit_categories_retrieve_update",
#     ),
#     re_path(
#         r"api/v1/visit-types$",
#         VisitTypesListCreateBulkAPIView.as_view(),
#         name="list_create_visit_types",
#     ),
#     re_path(
#         r"api/v1/visit-types/(?P<pk>[0-9a-zA-Z\-]+)$",
#         VisitTypesRetrieveUpdateAPIView.as_view(),
#         name="visit_types_retrieve_update",
#     ),
#     re_path(
#         r"api/v1/visit-type-templates$",
#         VisitTypeTemplatesListCreateAPIView.as_view(),
#         name="visit_types_templates_list_create",
#     ),
#     re_path(
#         r"api/v1/visit-type-templates/(?P<pk>[0-9a-zA-Z\-]+)$",
#         VisitTypeTemplatesRetrieveUpdateAPIView.as_view(),
#         name="visit_types_templates_retrieve_update",
#     ),
#     re_path(
#         r"api/v1/visit-type-assignment-requests$",
#         VisitTypeAssignmentRequestListCreateAPIView.as_view(),
#         name="visit_types_assignment_request_list_create",
#     ),
# ]
