namespace Resido.Model.TTLockDTO.RequestDTO.LockSettingRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class SetAutoLockTimeRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// The lock will automatically lock after the specific seconds.
        /// Set 0 or -1 to disable auto lock.
        /// </summary>
        public int Seconds { get; set; }

        /// <summary>
        /// Method of setting auto lock time (1 = Bluetooth, 2 = Cloud).
        /// </summary>
        public OperationType Type { get; set; } = OperationType.Bluetooth;
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockSetAutoLockTimeRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int Seconds { get; set; }
        public int Type { get; set; }
        public string AccessToken { get; set; }
    }

}
