# Generated by Django 4.2.16 on 2025-05-28 09:28

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "prefix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="PREFIX", max_length=50, null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=512)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("last_name", models.CharField(max_length=512)),
                (
                    "previous_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("suffix", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "email",
                    models.CharField(
                        db_index=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=25, null=True)),
                ("dob", models.DateField()),
                (
                    "gender",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="GENDER_TYPE", max_length=255, null=True
                    ),
                ),
                ("ssn", models.CharField(blank=True, max_length=50, null=True)),
                ("employer_detail", models.JSONField(default=list)),
                (
                    "status",
                    lookup.fields.LookupField(
                        blank=True,
                        default="APPROVED",
                        lookup_name="USER_ACTIVATION_STATUS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="OCCUPATION", max_length=100, null=True
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_guest_patient", models.BooleanField(default=False)),
                ("sms_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                ("failed_attempt_count", models.IntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentRegisteredDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("mac_address", models.CharField(max_length=255)),
                ("os_detail", models.CharField(max_length=255)),
                ("last_ip_address", models.CharField(max_length=255)),
                ("last_location", models.JSONField(blank=True, null=True)),
                (
                    "device_token",
                    models.CharField(
                        blank=True, max_length=1024, null=True, unique=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "make", "model", "mac_address")},
            },
        ),
        migrations.CreateModel(
            name="ResidentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "document_type",
                    lookup.fields.LookupField(
                        lookup_name="IDENTITY_LIST", max_length=40
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="back_image",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "front_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="front_image",
                        to="assets.asset",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("refresh_exp", models.DateTimeField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(max_length=255)),
                ("location", models.JSONField()),
                (
                    "login_status",
                    models.CharField(
                        choices=[
                            ("success", "Successful Sign-In"),
                            ("failure", "Unsuccessful Sign-In"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residents.residentregistereddevice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "home_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("home_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cell_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("cell_no", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.JSONField(default=[{}])),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "gender",
                    lookup.fields.LookupField(lookup_name="GENDER_TYPE", max_length=30),
                ),
                (
                    "relationship",
                    lookup.fields.LookupField(
                        blank=True,
                        lookup_name="PATIENT_RELATIONSHIP",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "relationship",
                    lookup.fields.LookupField(
                        blank=True,
                        lookup_name="PATIENT_RELATIONSHIP",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_family",
                        to="residents.resident",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_resident",
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "member")},
            },
        ),
    ]
