# Generated by Django 4.2.16 on 2025-05-28 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resident",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
