# Generated by Django 4.2.16 on 2025-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0002_alter_resident_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="resident_id",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
