# Generated by Django 4.2.16 on 2025-05-28 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0003_resident_resident_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="employer_detail",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="employer_name",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="fax_country_code",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="is_guest_patient",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="phone_country_code",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="prefix",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="previous_name",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="status",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="suffix",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="work_country_code",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="work_phone",
        ),
    ]
