# Generated by Django 4.2.16 on 2025-05-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0004_remove_resident_dob_remove_resident_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="profile_type",
            field=models.CharField(
                choices=[("owner", "OWNER"), ("tenant", "TENANT")],
                default="tenant",
                max_length=200,
            ),
        ),
    ]
