# Generated by Django 4.2.16 on 2025-06-11 12:50

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("residents", "0005_resident_profile_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="address",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="city",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="country",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="state",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="resident",
            name="communication_mode",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="COMMUNICATION_MODE", max_length=200
                ),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="emergency_alerts_communication",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="COMMUNICATION_MODE", max_length=200
                ),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="maintenance_communication",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="COMMUNICATION_MODE", max_length=200
                ),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="rent_notices_communication",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="COMMUNICATION_MODE", max_length=200
                ),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="residentdocument",
            name="document_data",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="ResidentFinancialGurantors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "include_in_notice",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_primary",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "relationship",
                    lookup.fields.LookupField(
                        lookup_name="OCCUPANTS_RELATIONSHIP", max_length=10
                    ),
                ),
                (
                    "communication_mode",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="COMMUNICATION_MODE", max_length=200
                        ),
                        blank=True,
                        default=[],
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "languages_known",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="LANGUAGE", max_length=50
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentCoOccupants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "include_in_notice",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "relationship",
                    lookup.fields.LookupField(
                        lookup_name="OCCUPANTS_RELATIONSHIP", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
