# Generated by Django 4.2.16 on 2025-06-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
        (
            "residents",
            "0006_remove_resident_address_remove_resident_address_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="residentdocument",
            name="back_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="resident_document_back_image",
                to="assets.asset",
            ),
        ),
        migrations.AlterField(
            model_name="residentdocument",
            name="front_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="resident_document_front_image",
                to="assets.asset",
            ),
        ),
    ]
