# Generated by Django 4.2.16 on 2025-07-01 06:01

from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0007_alter_residentdocument_back_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="relationship",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="RESIDENT_RELATIONSHIP",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residentfamily",
            name="relationship",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="RESIDENT_RELATIONSHIP",
                max_length=200,
                null=True,
            ),
        ),
    ]
