# Generated by Django 4.2.16 on 2025-10-22 12:29

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("residents", "0008_alter_emergencycontact_relationship_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentEviction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "notice_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "select_reason",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="EVICTION_REASON", max_length=200
                        ),
                        blank=True,
                        default=[],
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "custom_reason",
                    models.CharField(
                        blank=True,
                        help_text="Specify reason if 'Other' is selected",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notice_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("notice_date", models.DateField()),
                ("vacate_by_date", models.DateField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_on", models.DateField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("Email Notification", "EMAIL_NOTIFICATION"),
                            ("In-Person Delivery", "IN_PERSON_DELIVERY"),
                        ],
                        default="Email Notification",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "PENDING"), ("Sent", "SENT")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="resident_eviction_document",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
