# Generated by Django 4.2.16 on 2025-10-29 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0009_residenteviction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenteviction",
            name="delivery_method",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sms", "SMS"),
                        ("Email Notification", "EMAIL_NOTIFICATION"),
                        ("In-Person Delivery", "IN_PERSON_DELIVERY"),
                    ],
                    default="Email Notification",
                    max_length=30,
                ),
                size=None,
            ),
        ),
    ]
