# Generated by Django 4.2.16 on 2025-10-30 05:24

from django.db import migrations, models
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0010_alter_residenteviction_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="residenteviction",
            name="reject_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residenteviction",
            name="reject_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residenteviction",
            name="reject_reason",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="MAINTENANCE_REJECT_REASON",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residenteviction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Sent", "SENT"),
                    ("rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
