# Generated by Django 4.2.16 on 2025-11-12 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0012_residentregistereddevice_device_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenteviction",
            name="delivery_method",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("SMS", "SMS"),
                        ("EMAIL", "EMAIL_NOTIFICATION"),
                        ("In-Person Delivery", "IN_PERSON_DELIVERY"),
                    ],
                    default="EMAIL",
                    max_length=30,
                ),
                size=None,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="residentregistereddevice",
            unique_together={
                ("user", "device_fingerprint"),
                ("user", "make", "model", "mac_address"),
            },
        ),
    ]
