# Generated by Django 4.2.16 on 2025-05-20 18:05

import concurrency.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "acc_type",
                    models.CharField(
                        blank=True, default="prov", max_length=100, null=True
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "work_phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "cell_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "cell_phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "fax",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                ("emails", models.JSONField(default=[{}])),
                (
                    "communication_mode",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True,
                            lookup_name="COMMUNICATION_MODE",
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicLab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("payer_id", models.CharField(max_length=100)),
                ("payer_name", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("group_npi", models.CharField(blank=True, max_length=15, null=True)),
                ("allow_ext_providers", models.BooleanField(default=True)),
                ("max_security_question", models.IntegerField(default=10)),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "direct_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_communication_mode",
                    models.CharField(
                        choices=[
                            ("EM", "Email"),
                            ("WP", "Work phone"),
                            ("CP", "Cell phone"),
                            ("FAX", "Fax"),
                            ("ML", "Mail"),
                            ("ALL", "All"),
                        ],
                        default="ÁLL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customer_url",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "entity",
                    lookup.fields.LookupField(
                        blank=True,
                        default="INT",
                        lookup_name="ORG_ENTITY",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "practice_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("brand_color", models.CharField(default="#3B1550", max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("tax_id", models.CharField(max_length=40)),
                ("provider_tax_id", models.CharField(max_length=40)),
                ("gl_code", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "acccounts_payable",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("routing_num", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_acc", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_addr", models.CharField(blank=True, max_length=512, null=True)),
                ("bank_city", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_state", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_zip", models.CharField(blank=True, max_length=40, null=True)),
                ("hspa_qual", models.BooleanField(default=True)),
                (
                    "hspa_modifier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fin_email_add",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "fin_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fin_phone", models.CharField(blank=True, max_length=40, null=True)),
                ("fin_fax", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "second_address",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "second_address_1",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("second_city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "second_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "second_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "second_country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("group_npi", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "Health Center with this name already exists."
                        },
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    lookup.fields.LookupField(
                        default="prov", lookup_name="ORG_TYPE", max_length=100
                    ),
                ),
                (
                    "entity",
                    lookup.fields.LookupField(
                        blank=True,
                        default="INT",
                        lookup_name="ORG_ENTITY",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=100, null=True)),
                (
                    "billing_contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cell_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("cell_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            blank=True, max_length=254, null=True
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "communication_mode",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True,
                            lookup_name="COMMUNICATION_MODE",
                            max_length=200,
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "languages_known",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True, lookup_name="LANGUAGE", max_length=50, null=True
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "healthcenter_emr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "role_in_healthcenter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEO", "CEO"),
                            ("CMO", "CMO"),
                            ("Practice Administrator", "practice_administrator"),
                            (
                                "Clinic Manager / Medical Office Manager",
                                "clinic_manager_medical_office_manager",
                            ),
                            ("Credentialing Specialist", "credentialing_specialist"),
                            ("IT Administrator", "IT_administrator"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        blank=True, default="#3B1550", max_length=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="locations.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finances",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="hc_finance",
                        to="locations.financialdetails",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "group_npi")},
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INT", "Internal"), ("EXT", "External")],
                        default="INT",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "second_address",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "second_address_1",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("second_city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "second_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "second_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "second_country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("group_npi", models.CharField(blank=True, max_length=15, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("payable_to", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "billing_contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "latlng",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cell_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("cell_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "entity",
                    lookup.fields.LookupField(
                        blank=True,
                        default="INT",
                        lookup_name="ORG_ENTITY",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "direct_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                ("addresses", models.JSONField(default=list)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            blank=True, max_length=254, null=True
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "communication_mode",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True,
                            lookup_name="COMMUNICATION_MODE",
                            max_length=100,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "languages_known",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True, lookup_name="LANGUAGE", max_length=50, null=True
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "type",
                    lookup.fields.LookupField(
                        default="AF", lookup_name="FACILITY_TYPE", max_length=100
                    ),
                ),
                ("accepts_new_patient", models.BooleanField(default=True)),
                ("provides_telehealth", models.BooleanField(default=True)),
                ("is_urgent_care", models.BooleanField(default=False)),
                ("clia_id", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "mammography_cert_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("sales_tax", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "sate_immu_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("exam_rooms", models.JSONField(default=[])),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="health_center",
                        to="locations.healthcenter",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "labs",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="clinic_labs",
                        to="locations.cliniclab",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner",
                        to="locations.partner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "group_npi")},
            },
        ),
        migrations.CreateModel(
            name="VisitTypeDuration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "visit_type",
                    lookup.fields.LookupField(
                        default="NP_PHY", lookup_name="VISIT_TYPE", max_length=100
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practice_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="locations.practicelocation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeLocationFinancial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("npi", models.CharField(max_length=15, unique=True)),
                ("tax_id", models.CharField(max_length=40)),
                ("provider_tax_id", models.CharField(max_length=40)),
                ("gl_code", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "acccounts_payable",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("routing_num", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_acc", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "bank_acc_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("bank_addr", models.CharField(blank=True, max_length=512, null=True)),
                ("bank_city", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_state", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_zip", models.CharField(blank=True, max_length=40, null=True)),
                ("hspa_qual", models.BooleanField(default=True)),
                (
                    "hspa_modifier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fin_email_add",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "fin_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fin_phone", models.CharField(blank=True, max_length=40, null=True)),
                ("fin_fax", models.CharField(blank=True, max_length=40, null=True)),
                ("clia_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "mammography_certified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_BUSINESS_TYPE"),
                ),
                (
                    "location_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_LOCATION_TYPE"),
                ),
                (
                    "place_of_service_code",
                    lookup.fields.LookupField(lookup_name="PLACE_OF_SERVICE"),
                ),
                (
                    "bank_account_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_BANK_ACCOUNT_TYPE"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.healthcenter",
                    ),
                ),
                (
                    "practice_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="locations.practicelocation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthCenterFinancial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("npi", models.CharField(max_length=15, unique=True)),
                ("tax_id", models.CharField(max_length=40)),
                ("provider_tax_id", models.CharField(max_length=40)),
                ("gl_code", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "acccounts_payable",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("routing_num", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_acc", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "bank_acc_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("bank_addr", models.CharField(blank=True, max_length=512, null=True)),
                ("bank_city", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_state", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_zip", models.CharField(blank=True, max_length=40, null=True)),
                ("hspa_qual", models.BooleanField(default=True)),
                (
                    "hspa_modifier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fin_email_add",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "fin_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fin_phone", models.CharField(blank=True, max_length=40, null=True)),
                ("fin_fax", models.CharField(blank=True, max_length=40, null=True)),
                ("clia_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "mammography_certified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_BUSINESS_TYPE"),
                ),
                (
                    "location_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_LOCATION_TYPE"),
                ),
                (
                    "place_of_service_code",
                    lookup.fields.LookupField(lookup_name="PLACE_OF_SERVICE"),
                ),
                (
                    "bank_account_type",
                    lookup.fields.LookupField(lookup_name="FINANCE_BANK_ACCOUNT_TYPE"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="locations.healthcenter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountsFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "work_phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "cell_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                (
                    "cell_phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "fax",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "contact_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        blank=True,
                        default=[],
                        size=None,
                    ),
                ),
                ("emails", models.JSONField(default=[{}])),
                ("url", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "acc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_id",
                        to="locations.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_health_center",
                        to="locations.healthcenter",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "practice_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_location",
                        to="locations.practicelocation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="health_center",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="hc_acc",
                to="locations.healthcenter",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="practice_location",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="facility",
                to="locations.practicelocation",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
