# Generated by Django 4.2.16 on 2025-05-22 19:02

import concurrency.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import djmoney.models.fields
import lookup.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_floors", models.IntegerField()),
                ("year_built", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("floor_number", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "billing_contact_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_contact_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "billing_address_1",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "billing_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "billing_country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("payable_to", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "latlng",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "billing_contact_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_contact_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "billing_address_1",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "billing_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "billing_country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "Health Center with this name already exists."
                        },
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, max_length=100, null=True)),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "brand_color",
                    models.CharField(
                        blank=True, default="#3B1550", max_length=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("unit_number", models.CharField(max_length=255)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[("owned", "OWNED"), ("rental", "RENTAL")],
                        max_length=50,
                    ),
                ),
                ("is_furnished", models.BooleanField(default=False)),
                (
                    "furnished_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "furnished_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "unfurnished_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "unfurnished_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "hoa_fee_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "hoa_fee",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vancant", "VACANT"),
                            ("occupied", "OCCUPIED"),
                            ("move_out_scheduled", "MOVE_OUT_SCHEDULED"),
                            ("under_maintenance", "UNDER_MAINTENANCE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "unit_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("floor_plan", models.CharField(max_length=255)),
                ("is_pet_allowed", models.BooleanField(default=False)),
                ("is_service_animal_allowed", models.BooleanField(default=False)),
                ("pet_policy", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="account",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="account",
            name="health_center",
        ),
        migrations.RemoveField(
            model_name="account",
            name="image",
        ),
        migrations.RemoveField(
            model_name="account",
            name="practice_location",
        ),
        migrations.RemoveField(
            model_name="account",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="acc_id",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="health_center",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="image",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="practice_location",
        ),
        migrations.RemoveField(
            model_name="accountsfacility",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="cliniclab",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cliniclab",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="cliniclab",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="financialdetails",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="financialdetails",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="financialdetails",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="healthcenter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="finances",
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="image",
        ),
        migrations.RemoveField(
            model_name="healthcenter",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="healthcenterfinancial",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="healthcenterfinancial",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="healthcenterfinancial",
            name="health_center",
        ),
        migrations.RemoveField(
            model_name="healthcenterfinancial",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="practicelocation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="health_center",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="image",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="labs",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="practicelocation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="practicelocationfinancial",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="practicelocationfinancial",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="practicelocationfinancial",
            name="health_center",
        ),
        migrations.RemoveField(
            model_name="practicelocationfinancial",
            name="practice_location",
        ),
        migrations.RemoveField(
            model_name="practicelocationfinancial",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="visittypeduration",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="visittypeduration",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="visittypeduration",
            name="practice_location",
        ),
        migrations.RemoveField(
            model_name="visittypeduration",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="allow_ext_providers",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="direct_email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="group_npi",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="practice_type",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="preferred_communication_mode",
        ),
    ]
