# Generated by Django 4.2.16 on 2025-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locations",
            "0004_building_display_id_floor_display_id_unit_display_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="fax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="work_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="fax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="work_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="status",
            field=models.CharField(
                choices=[
                    ("vacant", "VACANT"),
                    ("occupied", "OCCUPIED"),
                    ("move_out_scheduled", "MOVE_OUT_SCHEDULED"),
                    ("under_maintenance", "UNDER_MAINTENANCE"),
                ],
                max_length=50,
            ),
        ),
    ]
