# Generated by Django 4.2.16 on 2025-06-06 08:20

from django.db import migrations, models
import djmoney.models.fields
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
        ("locations", "0005_alter_customer_fax_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="fax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="fax_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="work_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="work_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="deposit_refundable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="exceeding_occupancy_fee",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="exceeding_occupancy_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="extra_parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="extra_parking_charges",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="extra_parking_charges_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="furnished_security_deposit",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="furnished_security_deposit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="images",
            field=models.ManyToManyField(blank=True, null=True, to="assets.asset"),
        ),
        migrations.AddField(
            model_name="unit",
            name="max_unit_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_agressive_breed_allowed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_breed",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_BREED", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_fees_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_fees_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_fees_type",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_FEE_TYPE", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_max_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_security_deposit_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_security_deposit_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_security_deposit_refundable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_species",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_SPECIES", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unfurnished_security_deposit",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unfurnished_security_deposit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
