# Generated by Django 4.2.16 on 2025-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_location_email_location_fax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
