# Generated by Django 4.2.16 on 2025-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_amenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="home_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="home_phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="home_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="home_phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="home_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="home_phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
    ]
