# Generated by Django 4.2.16 on 2025-09-17 04:40

from django.db import migrations, models
import django.db.models.deletion
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0005_alter_helixuser_languages_known_and_more"),
        (
            "locations",
            "0009_customer_home_phone_customer_home_phone_country_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="allow_smoking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="extra_parking_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electric Vehicle", "ELECTRIC_VEHICLE"),
                    ("Bicycle", "BICYCLE"),
                    ("Visitor", "VISITOR"),
                    ("Reserved", "RESERVED"),
                    ("Disabled", "DISABLED"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="lease_expiry_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="max_extra_spaces_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="max_occupancy_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="max_pets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="ownership",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="OWNERSHIP", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Two Wheeler", "TWO_WHEELER"),
                    ("Four Wheeler", "FOUR_WHEELER"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_type",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_TYPE", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="service_animal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("service_animal", "SERVICE_ANIMAL"),
                    ("esa", "ESA"),
                    ("both", "BOTH"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="smoking_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "YES"),
                    ("no", "NO"),
                    ("outside_only", "OUTSIDE_ONLY"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="violation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units_with_violation_policy",
                to="helixauth.policy",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="floor_plan",
            field=lookup.fields.LookupField(lookup_name="FLOOR_PLAN", max_length=100),
        ),
        migrations.AlterField(
            model_name="unit",
            name="pet_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units_with_pet_policy",
                to="helixauth.policy",
            ),
        ),
    ]
