# Generated by Django 4.2.16 on 2025-09-17 04:56

from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0010_unit_allow_smoking_unit_extra_parking_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="pet_breed",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_BREED", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="pet_species",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_SPECIES", max_length=50, null=True
            ),
        ),
    ]
