# Generated by Django 4.2.16 on 2025-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0011_alter_unit_pet_breed_alter_unit_pet_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
