# Generated by Django 4.2.16 on 2025-10-31 07:23

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0013_parkinglevel_parkingzone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingzone",
            name="total_slots",
        ),
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("slot_no", models.CharField(max_length=20)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("large", "LARGE"),
                            ("ev", "EV"),
                            ("compact", "COMPACT"),
                            ("bike", "BIKE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("unavailable", "UNAVAILABLE"),
                            ("vip_only", "VIP_ONLY"),
                            ("electric_charging_only", "ELECTRIC_CHARGING_ONLY"),
                            ("disabled_access_only", "DISABLED_ACCESS_ONLY"),
                            ("out_of_service", "OUT_OF_SERVICE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="locations.parkingzone",
                    ),
                ),
            ],
            options={
                "unique_together": {("zone", "slot_no")},
            },
        ),
    ]
