# Generated by Django 4.2.16 on 2025-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0014_remove_parkingzone_total_slots_parkingslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="inactive_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
