# Generated by Django 4.2.16 on 2025-12-04 12:01
# Comprehensive squashed migration combining all parking, charges, and policy changes

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):
    replaces = [
        ("locations", "0016_add_parking_fields"),
        ("locations", "0017_add_parking_zone_field"),
        ("locations", "0018_add_administration_charges"),
        ("locations", "0019_add_unit_charges_and_violation_policies"),
        ("locations", "0020_change_pet_policy_to_many_to_many"),
    ]

    dependencies = [
        ("locations", "0015_add_inactive_on_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("helixauth", "0007_add_device_fingerprint_to_registereddevice"),
    ]

    operations = [
        # Add parking fields to Unit
        migrations.AddField(
            model_name="unit",
            name="accessible_parking_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="additional_parking_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="additional_parking_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="guest_parking_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_separate_parking_lease_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="no_of_spaces_per_unit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_allowed_at_complex_level",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_allowed_at_unit_level",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_included_in_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_slots",
            field=models.ManyToManyField(
                blank=True, related_name="units", to="locations.parkingslot"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="parking_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units_in_zone",
                to="locations.parkingzone",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="admin_charges_applicable",
            field=models.BooleanField(default=False),
        ),
        # Remove old single-value policy fields
        migrations.RemoveField(
            model_name="unit",
            name="violation_policy",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="pet_policy",
        ),
        # Add new many-to-many policy fields
        migrations.AddField(
            model_name="unit",
            name="violation_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="units_with_violation_policies",
                to="helixauth.policy",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pet_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="units_with_pet_policies",
                to="helixauth.policy",
            ),
        ),
        # Create UnitAdministrationCharge model for multiple charges per unit
        migrations.CreateModel(
            name="UnitAdministrationCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("charge_name", models.CharField(max_length=255)),
                (
                    "charge_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "charge_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="USD", max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administration_charges",
                        to="locations.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
