# Generated by Django 4.2.16 on 2025-12-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
        ("locations", "0016_add_parking_and_policies_squashed_0020"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer_favicon",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer_logo",
                to="assets.asset",
            ),
        ),
    ]
