# Generated by Django 4.2.16 on 2026-01-21 13:05

from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0022_unit_pdf_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="parking_type",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PARKING_TYPE", max_length=32, null=True
            ),
        ),
    ]
