# Generated by Django 4.2.16 on 2026-01-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_petspecies_petbreed"),
        ("locations", "0022_unit_pdf_asset"),
    ]

    operations = [
        # Clear existing lookup string values before converting to ForeignKey
        migrations.RunSQL(
            sql="UPDATE locations_unit SET pet_breed = NULL, pet_species = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="unit",
            name="pet_breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="common.petbreed",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="pet_species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="common.petspecies",
            ),
        ),
    ]
