# Generated by Django 4.2.16 on 2026-01-24 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0023_alter_unit_parking_type"),
        ("locations", "0023_alter_unit_pet_breed_alter_unit_pet_species"),
    ]

    operations = []
