from django.urls import re_path
from digitalforms.apiviews import (
    CategoryGetUpdateView,
    CategoryListCreateView,
    ApprovalTeamGetUpdateView,
    ApprovalTeamListCreateView,
    FormListCreateView,
    FormGetUpdateView,
    DigitalFormsCountView,
    FormSectionListCreateView,
    FormSectionGetUpdateView,
    FormRowListCreateView,
    FormRowGetUpdateView,
    FormFieldListCreateView,
    FormFieldGetUpdateView,
    FieldListCreateView,
    FieldGetUpdateView,
    WidgetListCreateView,
    WidgetGetUpdateView,
    WidgetRowListCreateView,
    WidgetRowGetUpdateView,
    WidgetFieldListCreateView,
    WidgetFieldGetUpdateView,
    FormReviewGetUpdateView,
    FormReviewListCreateView,
    FormVersionGetUpdateView,
    UserResponseGetUpdateView,
    UserResponseListCreateView,
)

urlpatterns = [
    re_path(
        r"^api/v1/digital-forms-fields$",
        FieldListCreateView.as_view(),
        name="df_fields_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-fields/(?P<pk>[0-9a-zA-Z\-]+)$",
        FieldGetUpdateView.as_view(),
        name="df_fields_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-categories$",
        CategoryListCreateView.as_view(),
        name="df_categories_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-categories/(?P<pk>[0-9a-zA-Z\-]+)$",
        CategoryGetUpdateView.as_view(),
        name="df_categories_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-approval-team$",
        ApprovalTeamListCreateView.as_view(),
        name="df_approval_team_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-approval-team/(?P<pk>[0-9a-zA-Z\-]+)$",
        ApprovalTeamGetUpdateView.as_view(),
        name="df_approval_team_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms$",
        FormListCreateView.as_view(),
        name="df_form_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormGetUpdateView.as_view(),
        name="df_form_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets$",
        WidgetListCreateView.as_view(),
        name="df_widget_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets/(?P<pk>[0-9a-zA-Z\-]+)$",
        WidgetGetUpdateView.as_view(),
        name="df_widget_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-counts$",
        DigitalFormsCountView.as_view(),
        name="df_form_counts",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormVersionGetUpdateView.as_view(),
        name="df_form_version_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/reviews$",
        FormReviewListCreateView.as_view(),
        name="df_rvw_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/reviews/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormReviewGetUpdateView.as_view(),
        name="df_rvw_update",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections$",
        FormSectionListCreateView.as_view(),
        name="df_sect_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormSectionGetUpdateView.as_view(),
        name="df_sect_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections/(?P<form_section_id>[0-9a-zA-Z\-]+)/rows$",
        FormRowListCreateView.as_view(),
        name="df_row_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections/(?P<form_section_id>[0-9a-zA-Z\-]+)/rows/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormRowGetUpdateView.as_view(),
        name="df_row_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections/(?P<form_section_id>[0-9a-zA-Z\-]+)/rows/(?P<form_row_id>[0-9a-zA-Z\-]+)/fields$",
        FormFieldListCreateView.as_view(),
        name="df_field_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-version/(?P<form_version_id>[0-9a-zA-Z\-]+)/sections/(?P<form_section_id>[0-9a-zA-Z\-]+)/rows/(?P<form_row_id>[0-9a-zA-Z\-]+)/fields/(?P<pk>[0-9a-zA-Z\-]+)$",
        FormFieldGetUpdateView.as_view(),
        name="df_field_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets/(?P<widget_id>[0-9a-zA-Z\-]+)/rows$",
        WidgetRowListCreateView.as_view(),
        name="dfw_row_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets/(?P<widget_id>[0-9a-zA-Z\-]+)/rows/(?P<pk>[0-9a-zA-Z\-]+)$",
        WidgetRowGetUpdateView.as_view(),
        name="dfw_row_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets/(?P<widget_id>[0-9a-zA-Z\-]+)/rows/(?P<widget_row_id>[0-9a-zA-Z\-]+)/fields$",
        WidgetFieldListCreateView.as_view(),
        name="dfw_field_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-widgets/(?P<widget_id>[0-9a-zA-Z\-]+)/rows/(?P<widget_row_id>[0-9a-zA-Z\-]+)/fields/(?P<pk>[0-9a-zA-Z\-]+)$",
        WidgetFieldGetUpdateView.as_view(),
        name="dfw_field_get_update",
    ),
    re_path(
        r"^api/v1/digital-forms-response$",
        UserResponseListCreateView.as_view(),
        name="df_resp_list_create",
    ),
    re_path(
        r"^api/v1/digital-forms-response/(?P<pk>[0-9a-zA-Z\-]+)$",
        UserResponseGetUpdateView.as_view(),
        name="df_resp_get_update",
    ),
]
