ERROR_DETAILS = {
    "token_not_valid": "Token is invalid or your session has expired. Please log in again.",
    "email_missing": "Email is required",
    "email_phone_missing": "Email or Phone Number is required",
    "username_or_password_missing": "Username or Password is missing",
    "resident_not_found": "No Resident exists with given identifier",
    "patient_partial_mismatch": "Patient with different information exists with same Contact information.",
    "patient_exists": "Patient already exists with given Email/Phone Number",
    "email_error": "Error occurred while sending email",
    "user_already_verified": "User already exists and is verified",
    "otp_missing": "otp is required",
    "cannot_update_data": "Cannot update the data of {field}",
    "no_active_user": "No active user found",
    "chart_not_signed": "Patient Chart is not yet signed by Provider to be locked",
    "invalid_otp_type": "Invalid value for otp_type parameter",
    "invalid_action": "Invalid value for action parameter",
    "user_id_type_missing": "user_id or user_type or both parameters are missing",
    "invalid_otp": "Invalid OTP",
    "invalid_choices": "Invalid choices provided for {attr}",
    "invalid_value": "Invalid value provided for {attr}",
    "invalid_answer": "Invalid answer",
    "user_not_found": "User Not Found",
    "user_role_not_found": "User Role Not Found",
    "module_not_found": "Module Not Found",
    "patient_chart_locked": "Patient chart is locked. So, no changes can be made to neither Encounter not Patient chart",
    "module_composition_not_found": "Module Composition Not Found",
    "module_permission_not_found": "Module Permission Not Found",
    "provider_id_missing": "Provider Id is required",
    "action_not_allowed": "Action is not allowed for current user",
    "encounter_not_found": "Encounter not found",
    "review_not_found": "Review not found",
    "update_timings_not_allowed": "Updating timings on the event is not allowed. Create Event Update object to modify"
    " time for single or all future occurrences.",
    "method_not_allowed": "Method Not Allowed",
    "slot_already_booked": "Slot is already booked",
    "invalid_slot_id": "Invalid slot",
    "visit_type_not_configured": "Visit Type is not configured for the staff",
    "invalid_name": "Invalid name provided",
    "provider_not_found": "Provider not found",
    "logout_device_required_missing": "Please pass all or device_id in request body",
    "insurance_company_not_found": "Insurance company not found",
    "insurance_exists_with_federal_ein": "Insurance company already exists with federal EIN",
    "patient_id_missing": "Patient Id is required parameter",
    "refresh_token_missing": "refresh_token is required parameter",
    "error_registering_patient": "Facing issue while registering patient in Auth Service",
    "something_went_wrong": "Something went wrong. Please try again.",
    "minors_check": "Minors are not allowed to do self registrations.",
    "invalid_user_type": "Invalid value for user_type parameter provided or this user_type is not allowed for this action.",
    "channel_not_allowed": "Channel is not allowed for this user",
    "appointment_already_in_status": "Appointment already in {status} status.",
    "status_not_allowed": "Status update not allowed due to missing required data or current status of the object",
    "cannot_reschedule_in_the_same_slot": "Cannot reschedule the appointment in the same slot",
    "invalid_password": "Invalid password",
    "not_allowed": "Not allowed",
    "email_or_password_missing": "Email or password is missing",
    "patient_does_not_exists": "Patient does not exist",
    "user_id_or_code_missing": "User ID or code is missing",
    "invalid_user_id": "Invalid user ID",
    "invalid_uuid": "Invalid UUID",
    "cannot_reset_password_of_guest_patient": "Cannot reset password of a guest patient",
    "email_and_phone_number_missing": "Email and Phone number is missing",
    "guest_patient_does_not_exist": "Guest Patient does not exist",
    "invalid_username": "Invalid username",
    "invalid_context": "Invalid context",
    "invalid_verification_data": "Invalid Verification Data",
    "patient_with_matching_details_exists": "Patient with matching details already exists",
    "invalid_patient_create_context": "Invalid context for creating patient",
    "guarantor_data_missing": "Guarantor data is missing",
    "search_data_not_found": "No Data found for the entered Location",
    "invalid_search": "Search should contain atleast 3 or more characters",
    "password_cannot_be_empty": "Password cannot be empty",
    "invalid_email": "Invalid email",
    "relation_or_family_missing": "Relationship or Family details are missing",
    "proxy_and_patient_unrelated": "Proxy and patient are not related",
    "latitude_longitude_coordinates_missing": "Latitude and Longitude Coordinates Missing",
    "search_criteria_missing": "Search Criteria Missing",
    "event_id_and_visit_type_missing": "Event ID and Visit Type Missing",
    "invalid_event_id_or_visit_type": "Invalid Event ID or Visit Type",
    "error_occurred_while_creating_slot": "Error occurred while creating slot",
    "proxy_patient_with_different_details_exists": "Proxy patient with same communication but "
    "different details already exists",
    "invalid_token": "The access token is invalid.",
    "type_required_param": "Type param is required for authenticate API",
    "req_param_missing": "One or more required params are missing",
    "specific_req_param_missing": "One or more required parameters are missing: {params}",
    "more_than_one_account": "More then one account registered",
    "invalid_code": "Invalid code",
    "incorrect_details": "Incorrect details. Please try again",
    "incorrect_password": "Incorrect password. Please try again",
    "account_locked": "Your account is locked. Please contact the administrator!",
    "no_mobile_linked": "No mobile number linked with user",
    "missing_notification_setting": "Configuration to send message is missing",
    "primary_count": "At least one and at most one {type} shall be primary",
    "user_locked": "User Locked out.",
    "invalid_input": "Input supplied is not valid",
    "invalid_input_value": "Input value supplied for {param} is not valid",
    "invalid_patient_id": "Invalid patient id",
    "invalid_renter_id": "Invalid renter id",
    "invalid_id": "Invalid id of {param} provided",
    "missing_required_param": "Required Parameter missing: {param}",
    "bill_not_found": "Bill not found",
    "error_payment": "Error occurred in processing the payment",
    "card_missing_payment": "Card is required when payment_method is 'card'",
    "account_missing_payment": "Account is required when payment_method is 'account'",
    "card_not_found": "Saved card not found",
    "account_not_found": "Saved account not found",
    "invalid_payment_method": "Invalid payment method",
    "invalid_amount": "Invalid amount",
    "invalid_cvv": "CVV is missing or invalid",
    "invalid_installment_date": "Installment date is missing or invalid",
    "payment_done": "Payment already done",
    "invalid_appointment_id": "Invalid appointment id provided",
    "invalid_encounter_id": "Invalid encounter id provided",
    "invalid_status": "Invalid status of {entity} for the action",
    "invalid_appointment_stage_for_action": "The action is not allowed at the current stage of Appointment",
    "intake_form_already_submitted": "The Intake Form has already been submitted for this appointment",
    "invalid_template_id": "Invalid template id provided",
    "invalid_value_json_data": "Invalid data structure of value_json provided",
    "missing_section": "Section is missing having name {name}",
    "missing_question_answers": "Question(s) are missing in section having name {name}",
    "invalid_request_structure": "The request structure of the api is wrong",
    "invalid_country_code": "Invalid country code - {country_code}",
    "invalid_phone_number": "Invalid phone number. Possibly, the phone number contains country code. "
    "Country code should be passed separately.",
    "meeting_not_found": "Meeting not found.",
    "meeting_participant_not_found": "Meeting participant not found.",
    "unknown_error_while_getting_token": "Unknown error while getting token",
    "invalid_phone_number_country_code": "Invalid phone number. Possibly, Missing phone number or country code.",
    "cannot_start_meeting": "Cannot start meeting. {reason}",
    "cannot_send_invite": "Cannot send invite. {reason}",
    "cannot_generate_token": "Cannot generate token. {reason}",
    "insurance_verification_id_missing": "Insurance verification id is missing",
    "invalid_insurance_verification_id": "Invalid insurance verification id",
    "invalid_content_type": "Invalid Content type for given user",
    "invalid_start_end_date": "Start date can not be greater than End date",
    "required_start_end_date": "Start date and End date are required",
    "not_able_to_send_sms": "Something went wrong while sending SMS.",
    "not_able_to_send_email": "Something went wrong while sending Email.",
    "user_role_inactive": "The user role is inactive",
    "invalid_access_level": "The access level selected is invalid.",
    "email_already_exists": "Email already exists",
    "email_does_not_exists": "Email does not exist",
    "email_required": "Email is required",
    "first_name_required": "First name is required",
    "last_name_required": "Last name is required",
    "phone_already_exists": "Phone number already exists",
    "cannot_deactivate_role": "This role is assigned to active users. Reassign it before deactivating",
    "search_filter_criteria_missing": "Search criteria and Filter Criteria both are missing. "
    "Search criteria must contain any one of the {search_criteria}. "
    "Filter criteria must contain any one of the {filter_criteria}. ",
    "inactive_user_exists": "Inactive user exists with the same email",
    "customer_admin_role_not_found": "Customer Admin role not found. Please create a role with the name 'Customer Admin'.",
    "onboarding_step_not_found": "Onboarding step not found",
    "onboarding_step_completed": "Onboarding step already completed",
    "email_or_code_missing": "Email or code is missing",
    "is_archive_error": "Archive status is missing",
    "health_center_or_location_not_found": "No Health Center or Location found",
    "customer_not_found": "Customer not found",
    "password_missing": "Password is missing",
    "invalid_request": "The request has expired or invalid",
    "name_already_exist": "A {class_name} with this {field_name} already exists",
    "meeting_id_missing": "Meeting ID is missing",
    "participants_data_missing": "Participants data is missing",
    "client_payment_status_missing": "Client Payment Status is missing",
    "payment_status_mismatch": "Payment status mismatch",
    "client_payment_response_missing": "Client Payment Response is missing",
    "invalid_status_for_cancellation": "Invalid status for_cancellation",
    "payment_missing_for_back_to_source": "Payment missing for back to source refund transaction",
    "payment_missing_for_cash": "Payment missing for cash refund transaction",
    "invalid_payment_ids": "Invalid payment ids - {payment_ids}",
    "invalid_bill_id": "Invalid bill ID - {bill_id}",
    "invalid_refund_type": "Invalid refund type",
    "total_refund_requested_too_large": "Total refund requested is larger than total refundable amount of the bill",
    "refund_requested_for_payment_too_large": "Refund requested for payment is too large - {payment_id}",
    "invalid_communication_details": "Provide valid communication details",
    "payment_status_missing": "Payment status is missing",
    "invalid_refund_method": "Invalid refund method",
    "invalid_transaction_type": "Invalid transaction type",
    "payment_not_found": "Payment not found",
    "error_cancel": "Error in cancelling payment transaction",
    "refund_failed": "Refund failed",
    "cannot_cancel": "Transaction cannot cancelled",
    "missing_bill_id": "Bill id not found",
    "invalid_list_of_user_ids": "A list of user IDs is required",
    "cannot_partially_refund": "Cannot partially refund transactions which were created less than 24 hours ago. "
    "Only full refund applicable for such transactions.",
    "unlocked_message": "Successfully unlocked {updated_count} users",
    "transaction_recon_job_not_found": "Transaction recon job not found for the tenant",
    "health_center_exists": "Health Center with this name already exists.",
    "cannot_update_speciality_or_seeded": "Can't update speciality or seeded flag",
    "cannot_update_category_or_seeded": "Can't update category or seeded flag",
    "default_visit_type_exists": "Default visit type already exists for the speciality - {speciality_name}",
    "employee_id_exists": "Employee with this id already exists.",
    "only_one_default_allowed": "Only one default visit type is allowed for a speciality.",
    "source_staff_and_speciality_required": "Source staff and speciality are required for assigning visit types",
    "source_template_required": "Source template is required for assigning visit types",
    "composition_required": "Composition is required for assigning visit types",
    "target_required": "Target staff ids are required for assigning visit types",
    "invalid_assignment_request_method": "Invalid assignment request method",
    "group_npi_exists": "Group NPI/NPI number already exist.",
    "duplicate_password": "Changed password matched with earlier password",
    "duplicate_name": "{field} with this name {field_name} already exists.",
    "activate_deactivate_message": "Successfully {action} {updated_count} user(s).",
    "user_ids_not_found": "No matching users found for the provided IDs",
    "staff_required_for_overridden_config": "Staff is required for overridden configurations",
    "source_staff_and_target_staff_cannot_be_same": "Source staff and target staff cannot be same",
    "access_level_fields_required": "{field} is required to fulfill user's access_level of {access_level}",
    "no_file_provided": "No file provided",
    "file_reading_failed": "Failed to read Excel file",
    "columns_missed": "Missing columns",
    "all_zero_phone_number": "Phone number cannot contain only zeros",
    "invalid_phone_format": "Enter a valid phone number",
    "slot_data_not_provided": "No slot data provided",
    "slot_start_end_mismatch": "start_slot_no cannot be greater than or equal to end_slot_no.",
    "invalid_zone_id": "Invalid zone_id provided.",
    "duplicate_floor_number": "A floor with this number already exists in the selected building.",
    "positive_rent_amount": "Rent amount must be a positive number",
    "invalid_due_date": "Due date/Expiry date cannot be before Start date",
    "end_date_required_for_fixed_term": "end_date is required for fixed-term leases.",
    "invalid_lease_term": "lease_term must be either 'fixed_term' or 'month_to_month'.",
    "application_not_found": "No application matching the provided IDs was found or you do not have permission to access it.",
    "duplicate_application": "An application for this resident and unit already exists.",
    "duplicate_service_details": "A service provider with the same (name, email, phone, home_phone, work_phone, contact_name, service_type) already exists",
    "invalid_account": "Invalid credentials. Please check your email and password.",
    "invalid_age_range": "Age must be between 0 and 150 years",
    "negative_age": "Age cannot be negative",
    "user_role_required": "Please select at least one role.",
}
