# Generated by Django 4.2.16 on 2025-06-05 13:06

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import lease.constants
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_initial"),
        ("locations", "0005_alter_customer_fax_alter_customer_phone_and_more"),
        ("digitalforms", "0001_initial"),
        ("residents", "0005_resident_profile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("filled", "FILLED"),
                            ("not_filled", "NOT_FILLED"),
                            ("background_check_started", "BACKGROUND_CHECK_STARTED"),
                            ("background_check_failed", "BACKGROUND_CHECK_FAILED"),
                            (
                                "background_check_completed",
                                "BACKGROUND_CHECK_COMPLETED",
                            ),
                            ("approved", "APPROVED"),
                            ("rejected", "REJECTED"),
                        ],
                        default=lease.constants.LeaseApplicationStatus["SENT"],
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="application",
                        to="digitalforms.formversion",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="application",
                        to="residents.resident",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="application",
                        to="locations.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ACTIVE"),
                            ("terminated", "TERMINATED"),
                            ("pending_renewal", "PENDING_RENEWAL"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "lease_term",
                    models.CharField(
                        choices=[
                            ("fixed_term", "FIXED_TERM"),
                            ("month_to_month", "MONTH_TO_MONTH"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rent_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "rent_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="USD", max_digits=14
                    ),
                ),
                ("due_date", models.DateField()),
                ("late_fees_applicable", models.BooleanField()),
                ("prorated_rent_applicable", models.BooleanField()),
                (
                    "prorated_rent_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "prorated_rent_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "deposit_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="USD", max_digits=14
                    ),
                ),
                ("deposit_refundable", models.BooleanField()),
                (
                    "security_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "security_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="USD", max_digits=14
                    ),
                ),
                ("security_refundable", models.BooleanField()),
                ("pet_deposit_required", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renewal", models.BooleanField()),
                ("one_time_fees_applicable", models.BooleanField()),
                (
                    "one_time_fees_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "one_time_fees_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "one_time_fees_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "payments_accepted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="PAYMENT_MODES", max_length=10
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "landlord_type",
                    models.CharField(
                        choices=[("individual", "INDIVIDUAL"), ("company", "COMPANY")],
                        max_length=100,
                    ),
                ),
                (
                    "landlord_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "landlord_middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "landlord_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "landlord_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("landlord_email", models.EmailField(max_length=254)),
                (
                    "landlord_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("yes", "YES"),
                            ("no", "NO"),
                            ("outside_only", "OUTSIDE_ONLY"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "parking_available",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            lookup_name="PARKING_TYPE", max_length=10
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("parking_rules", models.TextField(blank=True, null=True)),
                ("early_termination_allowed", models.BooleanField()),
                ("early_termination_clause", models.TextField(blank=True, null=True)),
                ("additional_terms_allowed", models.BooleanField()),
                ("additional_terms_clause", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="lease.application",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(blank=True, null=True, to="assets.asset"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "other_residents",
                    models.ManyToManyField(
                        related_name="lease", to="residents.resident"
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="leases",
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseUtilityServices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "service",
                    lookup.fields.LookupField(
                        lookup_name="UTILITY_SERVICE", max_length=10
                    ),
                ),
                (
                    "responsible",
                    models.CharField(
                        choices=[
                            ("tenant", "TENANT"),
                            ("landlord", "LANDLORD"),
                            ("na", "NA"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_services",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeasePetsAllowed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "type_of_pet",
                    lookup.fields.LookupField(lookup_name="TYPE_OF_PET", max_length=10),
                ),
                (
                    "breed",
                    lookup.fields.LookupField(lookup_name="PET_BREED", max_length=10),
                ),
                ("age", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets_allowed",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseOtherOccupants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "relationship",
                    lookup.fields.LookupField(
                        lookup_name="OCCUPANTS_RELATIONSHIP", max_length=10
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_occupants",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseLateFees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("one_time_fee_applicable", models.BooleanField(default=False)),
                (
                    "one_time_fee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "FLAT"),
                            ("percent_rent", "PERCENT_RENT"),
                            ("percent_unpaid", "PERCENT_UNPAID"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("one_time_fee_value", models.FloatField(blank=True, null=True)),
                (
                    "one_time_fee_applied_on",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "ONE_DAY_AFTER"),
                            (2, "TWO_DAYS_AFTER"),
                            (3, "THREE_DAYS_AFTER"),
                        ],
                        null=True,
                    ),
                ),
                ("daily_late_fee_applicable", models.BooleanField(default=False)),
                ("daily_late_fee", models.FloatField(blank=True, null=True)),
                (
                    "daily_late_fee_applied_on",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "ONE_DAY_AFTER"),
                            (2, "TWO_DAYS_AFTER"),
                            (3, "THREE_DAYS_AFTER"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "late_fee_limit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_limit", "NO_LIMIT"),
                            ("day_limit", "DAY_LIMIT"),
                            ("flat_limit", "FLAT_LIMIT"),
                            ("rent_limit", "RENT_LIMIT"),
                        ],
                        null=True,
                    ),
                ),
                ("late_fee_limit_value", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_fees",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseKeys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "key_type",
                    lookup.fields.LookupField(lookup_name="KEY_TYPE", max_length=10),
                ),
                ("copies", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseAdditionalSigners",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_signers",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
