# Generated by Django 4.2.16 on 2025-06-06 12:24

from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasepetsallowed",
            name="type_of_pet",
            field=lookup.fields.LookupField(lookup_name="PET_SPECIES", max_length=10),
        ),
    ]
