# Generated by Django 4.2.16 on 2025-06-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0002_alter_leasepetsallowed_type_of_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lease",
                to="lease.application",
            ),
        ),
    ]
