# Generated by Django 4.2.16 on 2025-06-12 13:51

from django.db import migrations, models
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0003_alter_lease_application"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="date",
            new_name="sent_date",
        ),
        migrations.RemoveField(
            model_name="application",
            name="form",
        ),
        migrations.AddField(
            model_name="application",
            name="approved_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="reject_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="reject_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="reject_reason",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="APPLICATION_REJECT_REASON",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "SENT"),
                    ("received", "RECEIVED"),
                    ("approved", "APPROVED"),
                    ("rejected", "REJECTED"),
                ],
                default="sent",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("draft", "DRAFT"),
                    ("active", "ACTIVE"),
                    ("terminated", "TERMINATED"),
                    ("pending_renewal", "PENDING_RENEWAL"),
                ],
                max_length=200,
            ),
        ),
    ]
