# Generated by Django 4.2.16 on 2025-06-16 11:53

from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0004_rename_date_application_sent_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="reject_reason",
            field=lookup.fields.LookupField(
                blank=True,
                lookup_name="APPLICATION_REJECT_REASON",
                max_length=100,
                null=True,
            ),
        ),
    ]
