# Generated by Django 4.2.16 on 2025-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0007_alter_residentdocument_back_image_and_more"),
        ("lease", "0005_alter_application_reject_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lease",
            name="deposit_amount_currency",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="one_time_fees_amount_currency",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="prorated_rent_amount_currency",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="rent_amount_currency",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="security_amount_currency",
        ),
        migrations.AlterField(
            model_name="lease",
            name="additional_terms_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="auto_renewal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="deposit_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lease",
            name="deposit_refundable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lease",
            name="early_termination_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lease",
            name="landlord_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="lease",
            name="landlord_type",
            field=models.CharField(
                blank=True,
                choices=[("individual", "INDIVIDUAL"), ("company", "COMPANY")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="late_fees_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="lease_term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed_term", "FIXED_TERM"),
                    ("month_to_month", "MONTH_TO_MONTH"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="one_time_fees_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lease",
            name="one_time_fees_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="other_residents",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="lease", to="residents.resident"
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="pet_deposit_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="prorated_rent_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lease",
            name="prorated_rent_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="rent_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lease",
            name="security_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lease",
            name="security_refundable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="smoking_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "YES"),
                    ("no", "NO"),
                    ("outside_only", "OUTSIDE_ONLY"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("draft", "DRAFT"),
                    ("active", "ACTIVE"),
                    ("terminated", "TERMINATED"),
                    ("pending_renewal", "PENDING_RENEWAL"),
                ],
                default="draft",
                max_length=200,
            ),
        ),
    ]
