# Generated by Django 4.2.16 on 2025-06-25 14:42

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lookup.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_initial"),
        ("lease", "0006_remove_lease_deposit_amount_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="esa_attachments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="lease_esa_attachment",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="esa_perform",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="esa_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("service_animal", "SERVICE_ANIMAL"),
                    ("esa", "ESA"),
                    ("both", "BOTH"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LeasePromotionalDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "name",
                    lookup.fields.LookupField(
                        lookup_name="LEASE_DISCOUNT", max_length=10
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotional_discount",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaseOneTimeFees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "name",
                    lookup.fields.LookupField(
                        lookup_name="LEASE_ONE_TIME_FEES", max_length=10
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_fees",
                        to="lease.lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
