# Generated by Django 4.2.16 on 2025-06-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "locations",
            "0009_customer_home_phone_customer_home_phone_country_code_and_more",
        ),
        ("lease", "0007_lease_esa_attachments_lease_esa_perform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lease",
                to="locations.unit",
            ),
        ),
    ]
