# Generated by Django 4.2.16 on 2025-06-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("helixauth", "0005_alter_helixuser_languages_known_and_more"),
        ("lease", "0008_lease_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="additional_terms_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="additional_terms_policy",
                to="helixauth.policyversion",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="early_termination_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="early_termination_policy",
                to="helixauth.policyversion",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="include_parking_rules",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lease",
            name="parking_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parking_policy",
                to="helixauth.policyversion",
            ),
        ),
    ]
