# Generated by Django 4.2.16 on 2025-06-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0009_lease_additional_terms_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaseadditionalsigners",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_signers",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leasekeys",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leaselatefees",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="late_fees",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leaseonetimefees",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="one_time_fees",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leaseotheroccupants",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_occupants",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leasepetsallowed",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets_allowed",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leasepromotionaldiscount",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotional_discount",
                to="lease.lease",
            ),
        ),
        migrations.AlterField(
            model_name="leaseutilityservices",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utility_services",
                to="lease.lease",
            ),
        ),
    ]
