# Generated by Django 4.2.16 on 2025-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0010_alter_leaseadditionalsigners_lease_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lease",
            old_name="address",
            new_name="landlord_address",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="address_1",
            new_name="landlord_address_1",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="city",
            new_name="landlord_city",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="country",
            new_name="landlord_country",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="state",
            new_name="landlord_state",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="zipcode",
            new_name="landlord_zipcode",
        ),
        migrations.RemoveField(
            model_name="leaselatefees",
            name="one_time_fee_applicable",
        ),
        migrations.RemoveField(
            model_name="leaselatefees",
            name="one_time_fee_applied_on",
        ),
        migrations.RemoveField(
            model_name="leaselatefees",
            name="one_time_fee_type",
        ),
        migrations.RemoveField(
            model_name="leaselatefees",
            name="one_time_fee_value",
        ),
        migrations.AddField(
            model_name="lease",
            name="landlord_phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
    ]
