# Generated by Django 4.2.16 on 2025-07-04 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0011_rename_address_lease_landlord_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lease",
            old_name="deposit_amount",
            new_name="pet_deposit_amount",
        ),
        migrations.RenameField(
            model_name="lease",
            old_name="deposit_refundable",
            new_name="pet_deposit_refundable",
        ),
    ]
