# Generated by Django 4.2.16 on 2025-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0012_rename_deposit_amount_lease_pet_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasepetsallowed",
            name="monthly_fee",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
