# Generated by Django 4.2.16 on 2025-09-19 14:13

from django.db import migrations, models
import django.db.models.manager
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0013_leasepetsallowed_monthly_fee"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="lease",
            managers=[
                ("analytics", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="lease",
            name="pet_type",
            field=lookup.fields.LookupField(
                blank=True, lookup_name="PET_TYPE", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="smoking_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("draft", "DRAFT"),
                    ("active", "ACTIVE"),
                    ("terminated", "TERMINATED"),
                    ("pending_renewal", "PENDING_RENEWAL"),
                    ("expired", "EXPIRED"),
                ],
                default="draft",
                max_length=200,
            ),
        ),
    ]
