# Generated by Django 4.2.16 on 2025-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0015_moverequest_moveinspectionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="display_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
