# Generated by Django 4.2.16 on 2025-10-28 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0016_application_display_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveinspectionlog",
            name="notify_renter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moveinspectionlog",
            name="preferred_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moveinspectionlog",
            name="preferred_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moverequest",
            name="deposit_status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("paid", "PAID")],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("draft", "DRAFT"),
                    ("active", "ACTIVE"),
                    ("terminated", "TERMINATED"),
                    ("eviction", "EVICTION"),
                    ("pending_renewal", "PENDING_RENEWAL"),
                    ("expired", "EXPIRED"),
                ],
                default="draft",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="moveinspectionlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("scheduled", "SCHEDULED"),
                    ("not_scheduled", "NOT_SCHEDULED"),
                    ("passed", "PASSED"),
                    ("failed", "FAILED"),
                ],
                default="not_scheduled",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="moveinspectionlog",
            constraint=models.UniqueConstraint(
                fields=("move_request", "preferred_date", "preferred_time"),
                name="unique_move_inspection_per_datetime",
            ),
        ),
    ]
