# Generated by Django 4.2.16 on 2025-10-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0017_moveinspectionlog_notify_renter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moveinspectionlog",
            name="move_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_requests",
                to="lease.moverequest",
            ),
        ),
    ]
