# Generated by Django 4.2.16 on 2025-10-29 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0018_alter_moveinspectionlog_move_request"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moveinspectionlog",
            name="unique_move_inspection_per_datetime",
        ),
        migrations.RemoveField(
            model_name="moveinspectionlog",
            name="preferred_date",
        ),
        migrations.RemoveField(
            model_name="moveinspectionlog",
            name="preferred_time",
        ),
        migrations.AddField(
            model_name="moveinspectionlog",
            name="preferred_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="moveinspectionlog",
            constraint=models.UniqueConstraint(
                fields=("move_request", "preferred_datetime"),
                name="unique_move_inspection_per_datetime",
            ),
        ),
    ]
