# Generated by Django 4.2.16 on 2025-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lease",
            "0019_remove_moveinspectionlog_unique_move_inspection_per_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moverequest",
            constraint=models.UniqueConstraint(
                fields=("unit", "resident", "move_type"),
                name="unique_move_request_per_move_type",
            ),
        ),
    ]
