# Generated by Django 4.2.16 on 2025-11-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0020_application_additional_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationadditionalleaseholders",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_additional_holders",
                to="lease.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationotheroccupants",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_other_occupants",
                to="lease.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationpetsallowed",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_pets_allowed",
                to="lease.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationutilityservices",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_utility_services",
                to="lease.application",
            ),
        ),
    ]
