# Generated by Django 4.2.16 on 2025-11-12 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0020_lease_pdf_asset"),
        ("lease", "0020_moverequest_unique_move_request_per_move_type"),
    ]

    operations = []
