# Generated by Django 4.2.16 on 2025-11-18 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0021_alter_applicationadditionalleaseholders_application_and_more"),
        ("lease", "0021_merge_20251112_1917"),
    ]

    operations = []
