# Generated by Django 4.2.16 on 2026-01-16 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0022_merge_20251118_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaseonetimefees",
            name="amount",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="leasepromotionaldiscount",
            name="amount",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
