# Generated by Django 4.2.16 on 2025-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0022_merge_20251118_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverequest',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
