# Generated by Django 4.2.16 on 2026-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0023_alter_leaseonetimefees_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="pending_activation_email",
            field=models.BooleanField(default=False),
        ),
    ]
