# Generated by Django 4.2.16 on 2026-01-19 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lease", "0023_moverequest_display_id"),
        ("lease", "0024_application_pending_activation_email"),
    ]

    operations = []
