# Generated by Django 4.2.16 on 2026-01-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_petspecies_petbreed"),
        ("lease", "0025_merge_20260119_1655"),
    ]

    operations = [
        # Drop NOT NULL constraint and clear existing lookup string values before converting to ForeignKey
        migrations.RunSQL(
            sql="""
                ALTER TABLE lease_applicationpetsallowed ALTER COLUMN type_of_pet DROP NOT NULL;
                ALTER TABLE lease_applicationpetsallowed ALTER COLUMN breed DROP NOT NULL;
                UPDATE lease_applicationpetsallowed SET breed = NULL, type_of_pet = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE lease_leasepetsallowed ALTER COLUMN type_of_pet DROP NOT NULL;
                ALTER TABLE lease_leasepetsallowed ALTER COLUMN breed DROP NOT NULL;
                UPDATE lease_leasepetsallowed SET breed = NULL, type_of_pet = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="applicationpetsallowed",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_pets",
                to="common.petbreed",
            ),
        ),
        migrations.AlterField(
            model_name="applicationpetsallowed",
            name="type_of_pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_pets",
                to="common.petspecies",
            ),
        ),
        migrations.AlterField(
            model_name="leasepetsallowed",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lease_pets",
                to="common.petbreed",
            ),
        ),
        migrations.AlterField(
            model_name="leasepetsallowed",
            name="type_of_pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lease_pets",
                to="common.petspecies",
            ),
        ),
    ]
