using Resido.Model.TTLockDTO.RequestDTO.CardRq;

namespace Resido.Model.TTLockDTO.RequestDTO.FingerPrintRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class AddFingerprintRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Fingerprint number (from APP SDK).
        /// </summary>
        public long FingerprintNumber { get; set; }

        /// <summary>
        /// Fingerprint type: 1 = normal, 4 = recurring.
        /// </summary>
        public int FingerprintType { get; set; } = 1;

        /// <summary>
        /// Optional: fingerprint name.
        /// </summary>
        public string? FingerprintName { get; set; }

        /// <summary>
        /// Start time when fingerprint becomes valid (timestamp in ms).
        /// </summary>
        public long StartDate { get; set; }

        /// <summary>
        /// End time when fingerprint expires (timestamp in ms).
        /// </summary>
        public long EndDate { get; set; }

        /// <summary>
        /// Optional: recurring time period for cyclic fingerprints.
        /// </summary>
        public List<CyclicConfigDTO>? CyclicConfig { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockAddFingerprintRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public long FingerprintNumber { get; set; }
        public int FingerprintType { get; set; }
        public string? FingerprintName { get; set; }
        public long StartDate { get; set; }
        public long EndDate { get; set; }
        public List<CyclicConfigDTO>? CyclicConfig { get; set; }
        public string AccessToken { get; set; }
    }
}
