namespace Resido.Model.TTLockDTO.RequestDTO.FingerPrintRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class RenameFingerprintRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Fingerprint ID to rename (from AddFingerprint response).
        /// </summary>
        public int FingerprintId { get; set; }

        /// <summary>
        /// New fingerprint name.
        /// </summary>
        public string FingerprintName { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockRenameFingerprintRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int FingerprintId { get; set; }
        public string FingerprintName { get; set; }
        public string AccessToken { get; set; }
    }

}
