using Resido.Model.TTLockDTO.RequestDTO;

namespace Resido.Model.TTLockDTO.ResponseDTO.PasscodeRsp
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class ChangeKeyboardPwdRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }

        /// <summary>
        /// Passcode ID to change.
        /// </summary>
        public int KeyboardPwdId { get; set; }

        /// <summary>
        /// Optional: new passcode name.
        /// </summary>
        public string? KeyboardPwdName { get; set; }

        /// <summary>
        /// Optional: new passcode value (4–9 digits).
        /// </summary>
        public string? NewKeyboardPwd { get; set; }

        /// <summary>
        /// Optional: start time when passcode becomes valid (timestamp in ms).
        /// Required if changing valid period.
        /// </summary>
        public long? StartDate { get; set; }

        /// <summary>
        /// Optional: end time when passcode expires (timestamp in ms).
        /// Required if changing valid period.
        /// </summary>
        public long? EndDate { get; set; }

        /// <summary>
        /// Method of change (1 = Bluetooth, 2 = Cloud).
        /// Only required when changing passcode itself or period.
        /// </summary>
        public OperationType? ChangeType { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockChangeKeyboardPwdRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public int KeyboardPwdId { get; set; }
        public string? KeyboardPwdName { get; set; }
        public string? NewKeyboardPwd { get; set; }
        public long? StartDate { get; set; }
        public long? EndDate { get; set; }
        public int? ChangeType { get; set; }
        public string AccessToken { get; set; }
    }

}
