from django.urls import re_path
import lease.apiviews as views

urlpatterns = [
    re_path(
        r"^api/v1/lease-application$",
        views.ApplicationListCreateView.as_view(),
        name="lease_app_list_create",
    ),
    re_path(
        r"^api/v1/lease-application-minimal$",
        views.ApplicationMinimalListView.as_view(),
        name="lease_app_minimal_list",
    ),
    re_path(
        r"^api/v1/lease-application-resend-invite$",
        views.ApplicationResendInviteView.as_view(),
        name="lease_app_resend_invite",
    ),
    re_path(
        r"^api/v1/lease-application-count$",
        views.ApplicationCountView.as_view(),
        name="lease_app_count",
    ),
    re_path(
        r"^api/v1/lease-application/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.ApplicationGetUpdateView.as_view(),
        name="lease_app_get_update",
    ),
    re_path(
        r"^api/v1/lease$",
        views.LeaseListCreateView.as_view(),
        name="lease_list_create",
    ),
    re_path(
        r"^api/v1/lease/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseGetUpdateView.as_view(),
        name="lease_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-count$",
        views.LeaseCountView.as_view(),
        name="lease_count",
    ),
    re_path(
        r"^api/v1/lease-late-fees$",
        views.LeaseLateFeesListCreateView.as_view(),
        name="lease_list_create",
    ),
    re_path(
        r"^api/v1/lease-late-fees/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseLateFeesGetUpdateView.as_view(),
        name="lease_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-other-occupants$",
        views.LeaseOtherOccupantsListCreateView.as_view(),
        name="lease_other_occupants_list_create",
    ),
    re_path(
        r"^api/v1/lease-other-occupants/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseOtherOccupantsGetUpdateView.as_view(),
        name="lease_other_occupants_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-additional-signers$",
        views.LeaseAdditionalSignersListCreateView.as_view(),
        name="lease_additional_signers_list_create",
    ),
    re_path(
        r"^api/v1/lease-additional-signers/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseAdditionalSignersGetUpdateView.as_view(),
        name="lease_additional_signers_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-pets-allowed$",
        views.LeasePetsAllowedListCreateView.as_view(),
        name="lease_pets_allowed_list_create",
    ),
    re_path(
        r"^api/v1/lease-pets-allowed/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeasePetsAllowedGetUpdateView.as_view(),
        name="lease_pets_allowed_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-utility-services$",
        views.LeaseUtilityServicesListCreateView.as_view(),
        name="lease_utility_services_list_create",
    ),
    re_path(
        r"^api/v1/lease-utility-services/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseUtilityServicesGetUpdateView.as_view(),
        name="lease_utility_services_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-keys$",
        views.LeaseKeysListCreateView.as_view(),
        name="lease_keys_list_create",
    ),
    re_path(
        r"^api/v1/lease-keys/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseKeysGetUpdateView.as_view(),
        name="lease_keys_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-one-time-fees$",
        views.LeaseOneTimeFeesListCreateView.as_view(),
        name="lease_one_time_fees_list_create",
    ),
    re_path(
        r"^api/v1/lease-one-time-fees/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseOneTimeFeesGetUpdateView.as_view(),
        name="lease_one_time_fees_list_get_update",
    ),
    re_path(
        r"^api/v1/lease-promotional-discount$",
        views.LeasePromotionalDiscountListCreateView.as_view(),
        name="lease_promotional_discount_list_create",
    ),
    re_path(
        r"^api/v1/lease-promotional-discount/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeasePromotionalDiscountGetUpdateView.as_view(),
        name="lease_promotional_discount_list_get_update",
    ),
    re_path(
        r"^api/v1/move-request$",
        views.MoveRequestListCreateAPIView.as_view(),
        name="moverequest_list_create",
    ),
    re_path(
        r"^api/v1/move-request-minimal$",
        views.MoveRequestMinimalListView.as_view(),
        name="moverequest_minimal_list",
    ),
    re_path(
        r"^api/v1/move-request/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.MoveRequestDetailUpdate.as_view(),
        name="moverequest_detail_update",
    ),
    re_path(
        r"^api/v1/move-request-count$",
        views.MoveRequestCountView.as_view(),
        name="moverequest_count",
    ),
    re_path(
        r"^api/v1/move-inspection$",
        views.MoveRequestInspectionListCreateAPIView.as_view(),
        name="move_inspection",
    ),
    re_path(
        r"^api/v1/move-inspection/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.MoveRequestInspectionDetailUpdate.as_view(),
        name="move_inspection",
    ),
    re_path(
        r"^api/v1/application-view/(?P<pk>[0-9a-zA-Z\-]+)$$",
        views.ApplicationVIewDetailUpdateAPIView.as_view(),
        name="application_view_update",
    ),
    re_path(
        r"^api/v1/property-detail/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.PropertyDetailAPIView.as_view(),
        name="property_detail",
    ),
    re_path(
        r"^api/v1/lease-minimal$",
        views.LeaseListCreateViewV2.as_view(),
        name="lease_list_create_v2",
    ),
    re_path(
        r"^api/v2/lease/(?P<pk>[0-9a-zA-Z\-]+)$",
        views.LeaseGetUpdateViewV2.as_view(),
        name="lease_get_update_v2",
    ),
]
