using Resido.Model.TTLockDTO.RequestDTO;

namespace Resido.Model.TTLockDTO.RequestDTO.GatewayRq
{
    /// <summary>
    /// Client-facing request DTO (no access token).
    /// </summary>
    public class UnlockLockRequestDTO
    {
        /// <summary>
        /// Lock ID, generated by Lock init.
        /// </summary>
        public int LockId { get; set; }
    }

    /// <summary>
    /// TTLock API request DTO (includes access token, clientId, date).
    /// </summary>
    public class TTLockUnlockLockRequestDTO : BaseRequestDTO, IAccessTokenRequest
    {
        public int LockId { get; set; }
        public string AccessToken { get; set; }
    }
}
