# Generated by Django 4.2.16 on 2025-05-20 18:05

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("helixauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelixStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "npi",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("is_provider", models.BooleanField(default=False)),
                (
                    "role_in_care_center",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEO", "CEO"),
                            ("CMO", "CMO"),
                            ("Practice Administrator", "practice_administrator"),
                            (
                                "Clinic Manager / Medical Office Manager",
                                "clinic_manager_medical_office_manager",
                            ),
                            ("Credentialing Specialist", "credentialing_specialist"),
                            ("IT Administrator", "IT_administrator"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("entity_type", models.IntegerField(default=1)),
                (
                    "provider_type",
                    lookup.fields.LookupField(
                        default="RESIDENT", lookup_name="PROVIDER_TYPE", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INT", "Internal"),
                            ("EXT", "External"),
                            ("ACT", "Account"),
                        ],
                        default="INT",
                        max_length=10,
                    ),
                ),
                (
                    "communication_mode",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=lookup.fields.LookupField(
                            blank=True,
                            lookup_name="COMMUNICATION_MODE",
                            max_length=200,
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "qualification",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=50, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("practice_since", models.DateField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("ratings_count", models.FloatField(blank=True, default=0, null=True)),
                (
                    "license_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_pcp", models.BooleanField(default=False)),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "work_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=25, null=True)),
                ("pac_id", models.CharField(blank=True, max_length=100, null=True)),
                ("enrol_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contractor_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dea_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dea_effective_date", models.DateField(blank=True, null=True)),
                ("dea_end_date", models.DateField(blank=True, null=True)),
                (
                    "medicaid_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_tin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("upin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_license_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_initials",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospital_affiliation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "hedis_rating",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qips", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "Employee with this id already exists."
                        },
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("pqip", models.CharField(blank=True, max_length=100, null=True)),
                ("pcam", models.CharField(blank=True, max_length=100, null=True)),
                ("cahps", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provider_credential_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "memberships",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "certifications",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "awards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("accepts_new_patient", models.BooleanField(default=True)),
                ("provides_telehealth", models.BooleanField(default=True)),
                (
                    "education",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("display_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "acc_id",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="acc_id_provider",
                        to="locations.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_customer",
                        to="locations.customer",
                    ),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True, null=True, to="locations.customer"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitTypeDuration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "visit_type",
                    lookup.fields.LookupField(
                        default="NP_PHY", lookup_name="VISIT_TYPE", max_length=100
                    ),
                ),
                ("duration", models.IntegerField(default=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="staff.helixstaff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("name", models.CharField(max_length=155, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NPIOverrides",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("npi", models.CharField(max_length=100)),
                ("npi_data", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="staff", to="staff.staffgroup"
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="health_centers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="health_centers",
                to="locations.healthcenter",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="provider_locations",
                to="locations.practicelocation",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="primary_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.practicelocation",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helixuser_staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_user_role",
                to="helixauth.userrole",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="user_roles",
            field=models.ManyToManyField(
                blank=True, null=True, to="helixauth.userrole"
            ),
        ),
    ]
