# Generated by Django 4.2.16 on 2025-05-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_building_floor_location_property_unit_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helixstaff",
            name="acc_id",
        ),
        migrations.AlterField(
            model_name="helixstaff",
            name="health_centers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="health_centers",
                to="locations.property",
            ),
        ),
        migrations.AlterField(
            model_name="helixstaff",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="provider_locations",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="helixstaff",
            name="primary_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
            ),
        ),
    ]
