# Generated by Django 4.2.16 on 2025-05-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locations",
            "0004_building_display_id_floor_display_id_unit_display_id_and_more",
        ),
        ("staff", "0002_remove_helixstaff_acc_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helixstaff",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="helixstaff",
            name="education",
        ),
        migrations.RemoveField(
            model_name="helixstaff",
            name="health_centers",
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="buildings",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="staff_buildings",
                to="locations.building",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="floors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="staff_floors", to="locations.floor"
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="properties",
                to="locations.property",
            ),
        ),
        migrations.AddField(
            model_name="helixstaff",
            name="units",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="staff_units", to="locations.unit"
            ),
        ),
        migrations.AlterField(
            model_name="helixstaff",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="staff_customers",
                to="locations.customer",
            ),
        ),
        migrations.AlterField(
            model_name="helixstaff",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="staff_locations",
                to="locations.location",
            ),
        ),
    ]
