# Generated by Django 4.2.16 on 2025-06-11 08:50

import django.contrib.postgres.fields
from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_remove_helixstaff_accepts_new_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helixstaff",
            name="communication_mode",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    blank=True,
                    lookup_name="COMMUNICATION_MODE",
                    max_length=200,
                    null=True,
                ),
                default=[],
                size=None,
            ),
        ),
    ]
