# Generated by Django 4.2.16 on 2025-06-17 09:34

import django.contrib.postgres.fields
from django.db import migrations
import lookup.fields


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_helixstaff_communication_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helixstaff",
            name="communication_mode",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=lookup.fields.LookupField(
                    lookup_name="COMMUNICATION_MODE", max_length=200
                ),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
    ]
