# Generated by Django 4.2.16 on 2025-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reason",
            unique_together={("category", "name")},
        ),
    ]
