from common.utils.enum import EnumWithValueConverter


class TemplateCode(EnumWithValueConverter):
    INCOMING_CALL = "INCOMING_CALL"
    MEETING_STARTED = "MEETING_STARTED"
    SCHEDULED_FACEMEET_INVITE = "SCHEDULED_FACEMEET_INVITE"
    QUICK_JOIN_FACEMEET_INVITE = "QUICK_JOIN_FACEMEET_INVITE"
    ACCOUNT_UNLOCK_NOTIFICATION = "ACCOUNT_UNLOCK_NOTIFICATION"
    ACCOUNT_ACTIVATE_NOTIFICATION = "ACCOUNT_ACTIVATE_NOTIFICATION"
    OTP_VERIFICATION = "OTP_VERIFICATION"
    FORGOT_PASSWORD = "FORGOT_PASSWORD"
    USER_ACCOUNT_CREATION = "USER_ACCOUNT_CREATION"

    EMAIL_CUSTOMER_ONBOARDING_SUCCESS = "email_customer_onboarding_success"
    EMAIL_CUSTOMER_DM_SUCCESS = "email_customer_dm_success"
    EMAIL_PROPERTY_CREATED = "email_property_created"
    EMAIL_LOCATION_CREATED = "email_location_created"
