from django.urls import re_path
import notifications.apiviews

urlpatterns = (
    re_path(
        r"^api/v1/patient/(?P<pk>[0-9a-zA-Z\-]+)/notifications$",
        notifications.apiviews.PatientPushNotifications.as_view(),
        name="patients_notifications_detail",
    ),
    re_path(
        r"^api/v1/notifications/messages$",
        notifications.apiviews.NotificationMessageList.as_view(),
        name="notification_message",
    ),
    re_path(
        r"^api/v1/notifications/summaries$",
        notifications.apiviews.NotificationSummaryList.as_view(),
        name="notification_summary_list",
    ),
    re_path(
        r"^api/v1/notifications/dls$",
        notifications.apiviews.NotificationDLList.as_view(),
        name="notification_dl",
    ),
    re_path(
        r"^api/v1/notifications/dls/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationDLDetail.as_view(),
        name="notification_dl_detail",
    ),
    re_path(
        r"^api/v1/notifications/templates$",
        notifications.apiviews.NotificationTemplateList.as_view(),
        name="notification_template",
    ),
    re_path(
        r"^api/v1/notifications/templates/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationTemplateDetail.as_view(),
        name="notification_template_detail",
    ),
    re_path(
        r"^api/v1/notifications/automated_messages$",
        notifications.apiviews.NotificationMessageAutomatedList.as_view(),
        name="auto_notification_message",
    ),
    re_path(
        r"^api/v1/notification/send_messages/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.SendNotificationMessge.as_view(),
        name="send_message",
    ),
    re_path(
        r"^api/v1/notification/automated_messages/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationMessageDetail.as_view(),
        name="notification_auto_message_detail",
    ),
    re_path(
        r"^api/v1/notification/user_dls$",
        notifications.apiviews.NotificationUserDLList.as_view(),
        name="notification_user_dl",
    ),
    re_path(
        r"^api/v1/notification/user_dls/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationUserDLDetail.as_view(),
        name="notification_user_dl_detail",
    ),
    re_path(
        r"^api/v1/notification/dl_files$",
        notifications.apiviews.NotificationDLFileList.as_view(),
        name="notification_user_dl_file",
    ),
    re_path(
        r"^api/v1/notification/dl_files/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationDLFileDetail.as_view(),
        name="notification_dl_file_detail",
    ),
    re_path(
        r"^api/v1/notifications/(?P<pk>[0-9a-zA-Z\-]+)$",
        notifications.apiviews.NotificationDetail.as_view(),
        name="notification_detail",
    ),
)
