# Generated by Django 4.2.16 on 2025-05-20 17:18

import concurrency.fields
from django.db import migrations, models
import django_tenants.postgresql_backend.base
import lookup.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthCareCustomer",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("address_1", models.CharField(blank=True, max_length=512, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="COUNTRY", max_length=10, null=True
                    ),
                ),
                (
                    "contact_prefix",
                    lookup.fields.LookupField(
                        blank=True,
                        default="Mr",
                        lookup_name="PREFIX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_suffix",
                    lookup.fields.LookupField(
                        blank=True, lookup_name="SUFFIX", max_length=100, null=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand_color", models.CharField(default="#3B1550", max_length=10)),
                ("slogan", models.CharField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "app_conf_type",
                    models.IntegerField(
                        choices=[(1, "Auto"), (2, "Manual")], default=1
                    ),
                ),
                ("allow_ext_providers", models.BooleanField(default=True)),
                ("url", models.CharField(max_length=100)),
                ("max_security_question", models.IntegerField(default=10)),
                ("code", models.IntegerField(unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "work_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "fax_country_code",
                    models.CharField(blank=True, default="+1", max_length=5, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferred_communication_mode",
                    models.CharField(
                        choices=[
                            ("EM", "Email"),
                            ("WP", "Work phone"),
                            ("CP", "Cell phone"),
                            ("FAX", "Fax"),
                            ("ML", "Mail"),
                            ("ALL", "All"),
                        ],
                        default="ÁLL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=100
                    ),
                ),
                ("group_npi", models.CharField(blank=True, max_length=100, null=True)),
                ("s2s_private_key", models.TextField(null=True)),
                ("s2s_public_key", models.TextField(null=True)),
                ("max_age_of_minor", models.IntegerField(default=12)),
                ("lockout_limit", models.IntegerField(default=5)),
                ("lockout_release_duration", models.IntegerField(default=1440)),
                ("realm", models.CharField(blank=True, max_length=100, null=True)),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_uuid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "realm_admin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "realm_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
