# Generated by Django 4.2.16 on 2025-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_country_alter_healthcarecustomer_fax_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcarecustomer",
            name="allow_ext_providers",
        ),
        migrations.RemoveField(
            model_name="healthcarecustomer",
            name="group_npi",
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
