# Generated by Django 4.2.16 on 2025-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_healthcarecustomer_allow_ext_providers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcarecustomer",
            name="home_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="home_phone_country_code",
            field=models.CharField(blank=True, default="+1", max_length=5, null=True),
        ),
    ]
