# Generated by Django 4.2.16 on 2025-11-10 08:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hb_core.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0005_healthcarecustomer_home_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthcarecustomer",
            old_name="home_phone",
            new_name="landmark",
        ),
        migrations.RemoveField(
            model_name="healthcarecustomer",
            name="home_phone_country_code",
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="contact_phone_country_code",
            field=models.CharField(
                blank=True,
                choices=[("+1", "USA"), ("+91", "IND")],
                default="+1",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="contact_phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="dmf_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="externally_sourced",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="language",
            field=models.CharField(blank=True, default="EN", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="login_method",
            field=models.CharField(
                choices=[("password", "PASSWORD"), ("otp", "OTP"), ("both", "BOTH")],
                default="password",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="master_customer_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="mfa_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[("EMAIL", "EMAIL"), ("PHONE", "PHONE")],
                default="EMAIL",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="remember_device_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="service_name",
            field=models.CharField(
                choices=[("common", "COMMON"), ("tenant", "TENANT")],
                default="common",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="source_of_data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="contact_first_name",
            field=hb_core.utils.fields.SafeCharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[+/%*^!@#$]", inverse_match=True
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="contact_last_name",
            field=hb_core.utils.fields.SafeCharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[+/%*^!@#$]", inverse_match=True
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="contact_middle_name",
            field=hb_core.utils.fields.SafeCharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[+/%*^!@#$]", inverse_match=True
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="fax",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="fax_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="phone",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="phone_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="work_country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarecustomer",
            name="work_phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
