# Generated by Django 5.1.1 on 2025-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_rename_home_phone_healthcarecustomer_landmark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_code",
            field=models.CharField(
                blank=True, default="INTERNAL", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_expires_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_name",
            field=models.CharField(
                blank=True, default="Internal", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_settings",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="plan_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="service_mode",
            field=models.CharField(
                choices=[("ISOLATED", "ISOLATED"), ("COLLABORATIVE", "COLLABORATIVE")],
                default="COLLABORATIVE",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="tier_code",
            field=models.CharField(
                blank=True, default="MEDIUM", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="tier_name",
            field=models.CharField(
                blank=True, default="Medium", max_length=100, null=True
            ),
        ),
    ]
