# Generated by Django 4.2.16 on 2025-12-29 11:31

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0008_healthcarecustomer_plan_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCareCustomerConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("is_payment_processing_enabled", models.BooleanField(default=False)),
                ("is_maintenance_module_enabled", models.BooleanField(default=False)),
                ("is_booking_module_enabled", models.BooleanField(default=False)),
                ("is_analytics_enabled", models.BooleanField(default=False)),
                ("is_digital_forms_enabled", models.BooleanField(default=False)),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("payment_grace_period_days", models.IntegerField(default=5)),
                ("late_fee_enabled", models.BooleanField(default=False)),
                ("auto_payment_reminder_days", models.IntegerField(default=3)),
                (
                    "maintenance_auto_assignment_enabled",
                    models.BooleanField(default=False),
                ),
                ("maintenance_sla_hours", models.IntegerField(default=24)),
                ("resident_portal_enabled", models.BooleanField(default=True)),
                ("self_service_enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="common.healthcarecustomer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Configuration",
                "verbose_name_plural": "Tenant Configurations",
            },
        ),
    ]
