# Generated by Django 4.2.16 on 2026-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_healthcarecustomerconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcarecustomer",
            name="display_id_v2",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="healthcarecustomer",
            name="prefix",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
